import type { Artist, Artwork, WeeklyFeature, Medium, Style, Theme, Event } from '@/types';

// Mock Artists - Based on actual artist names from files
export const mockArtists: Artist[] = [
  {
    _id: '1',
    name: 'arishdona',
    slug: 'arishdona',
    bio: 'Digital artist exploring creative visual narratives through contemporary digital art.',
    profileImageUrl: 'https://images.unsplash.com/photo-1494790108755-2616b612b77c?w=400&h=400&fit=crop&crop=face',
    socialLinks: [
      { platform: 'Instagram', url: 'https://instagram.com/arishdona' },
    ],
    status: 'active',
    createdAt: '2024-01-15',
    updatedAt: '2024-03-10',
  },
  {
    _id: '2',
    name: 'itsmeyourvicky',
    slug: 'itsmeyourvicky',
    bio: 'Contemporary digital artist known for vibrant compositions that capture modern aesthetics.',
    profileImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    socialLinks: [
      { platform: 'Instagram', url: 'https://instagram.com/itsmeyourvicky' },
    ],
    status: 'featured',
    createdAt: '2024-01-20',
    updatedAt: '2024-03-15',
  },
  {
    _id: '3',
    name: 'Phuong',
    slug: 'phuong',
    bio: 'Visual artist capturing moments and emotions through digital creativity.',
    profileImageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
    socialLinks: [
      { platform: 'Website', url: 'https://phuong.art' },
    ],
    status: 'active',
    createdAt: '2024-02-01',
    updatedAt: '2024-03-05',
  },
  {
    _id: '4',
    name: 'vadim064',
    slug: 'vadim064',
    bio: 'Digital creator focused on contemporary visual expressions and artistic innovation.',
    profileImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-02-05',
    updatedAt: '2024-03-08',
  },
  {
    _id: '5',
    name: '0xYANDY',
    slug: '0xyandy',
    bio: 'Digital artist creating immersive visual experiences through motion and design.',
    profileImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-02-10',
    updatedAt: '2024-03-12',
  },
  {
    _id: '6',
    name: 'Alexeyya',
    slug: 'alexeyya',
    bio: 'Creative artist exploring the boundaries between digital art and visual storytelling.',
    profileImageUrl: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-02-15',
    updatedAt: '2024-03-18',
  },
  {
    _id: '7',
    name: 'Kharather',
    slug: 'kharather',
    bio: 'Digital motion artist creating dynamic visual experiences.',
    profileImageUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-02-20',
    updatedAt: '2024-03-20',
  },
  {
    _id: '8',
    name: 'rawrage',
    slug: 'rawrage',
    bio: 'Artist expressing raw emotion and energy through digital visual media.',
    profileImageUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-02-25',
    updatedAt: '2024-03-25',
  },
  {
    _id: '9',
    name: 'Ahamedzola',
    slug: 'ahamedzola',
    bio: 'Creative mind behind humorous and engaging digital content.',
    profileImageUrl: 'https://images.unsplash.com/photo-1492562080023-c5b346fba1ae?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-01',
    updatedAt: '2024-03-28',
  },
  {
    _id: '10',
    name: 'Diokusumo',
    slug: 'diokusumo',
    bio: 'Digital artist specializing in contemporary visual narratives.',
    profileImageUrl: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-02',
    updatedAt: '2024-03-29',
  },
  {
    _id: '11',
    name: 'Nagasaikurma',
    slug: 'nagasaikurma',
    bio: 'Creative artist exploring modern digital expression.',
    profileImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-03',
    updatedAt: '2024-03-30',
  },
  {
    _id: '12',
    name: 'Fartxe',
    slug: 'fartxe',
    bio: 'Digital creator known for animated visual content.',
    profileImageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-04',
    updatedAt: '2024-03-31',
  },
  {
    _id: '13',
    name: 'dt-dude',
    slug: 'dt-dude',
    bio: 'Content creator specializing in engaging digital media.',
    profileImageUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-05',
    updatedAt: '2024-04-01',
  },
  {
    _id: '14',
    name: 'Katohife',
    slug: 'katohife',
    bio: 'Digital artist creating compelling visual stories.',
    profileImageUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-06',
    updatedAt: '2024-04-02',
  },
  {
    _id: '15',
    name: 'Richard12',
    slug: 'richard12',
    bio: 'Creative content producer in the digital art space.',
    profileImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-07',
    updatedAt: '2024-04-03',
  },
  {
    _id: '16',
    name: 'AlexGoldPack',
    slug: 'alexgoldpack',
    bio: 'GIF artist creating mesmerizing animated visuals.',
    profileImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-08',
    updatedAt: '2024-04-04',
  },
  {
    _id: '17',
    name: 'Grejk',
    slug: 'grejk',
    bio: 'Animated content creator specializing in dynamic visuals.',
    profileImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-09',
    updatedAt: '2024-04-05',
  },
  {
    _id: '18',
    name: 'johnathanhnd',
    slug: 'johnathanhnd',
    bio: 'Digital motion artist creating flowing animated experiences.',
    profileImageUrl: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-10',
    updatedAt: '2024-04-06',
  },
  {
    _id: '19',
    name: 'Kaygon',
    slug: 'kaygon',
    bio: 'GIF creator focused on nature-inspired animations.',
    profileImageUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-11',
    updatedAt: '2024-04-07',
  },
  {
    _id: '20',
    name: 'minhhnob',
    slug: 'minhhnob',
    bio: 'Digital wave artist creating fluid animated visuals.',
    profileImageUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-12',
    updatedAt: '2024-04-08',
  },
  {
    _id: '21',
    name: 'Misterche',
    slug: 'misterche',
    bio: 'Mysterious animated content creator.',
    profileImageUrl: 'https://images.unsplash.com/photo-1492562080023-c5b346fba1ae?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-13',
    updatedAt: '2024-04-09',
  },
  {
    _id: '22',
    name: 'newera3',
    slug: 'newera3',
    bio: 'Artist representing the new era of digital creativity.',
    profileImageUrl: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-14',
    updatedAt: '2024-04-10',
  },
  {
    _id: '23',
    name: 'Nook38',
    slug: 'nook38',
    bio: 'Cozy animated content creator bringing warmth through visuals.',
    profileImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-15',
    updatedAt: '2024-04-11',
  },
  {
    _id: '24',
    name: 'ricky1414',
    slug: 'ricky1414',
    bio: 'Rhythmic animator creating pulsing visual experiences.',
    profileImageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-16',
    updatedAt: '2024-04-12',
  },
  {
    _id: '25',
    name: 'Bikoy',
    slug: 'bikoy',
    bio: 'Motion graphics artist creating dynamic animated content.',
    profileImageUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=400&fit=crop&crop=face',
    status: 'active',
    createdAt: '2024-03-17',
    updatedAt: '2024-04-13',
  },
  // Weekly Features Artists - Arts
  {
    _id: '26',
    name: 'cuongquoc',
    slug: 'cuongquoc',
    bio: 'Featured digital artist exploring contemporary visual narratives.',
    profileImageUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '27',
    name: 'batuhantkmk',
    slug: 'batuhantkmk',
    bio: 'Video artist creating immersive digital experiences.',
    profileImageUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '28',
    name: 'haruvip',
    slug: 'haruvip',
    bio: 'Contemporary digital artist with a focus on visual storytelling.',
    profileImageUrl: 'https://images.unsplash.com/photo-1494790108755-2616b612b77c?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '29',
    name: 'himu_xyz',
    slug: 'himu_xyz',
    bio: 'Digital creator exploring innovative visual expressions.',
    profileImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '30',
    name: 'lika_enigma',
    slug: 'lika_enigma',
    bio: 'Enigmatic artist creating mysterious and captivating video art.',
    profileImageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '31',
    name: 'remwasdie',
    slug: 'remwasdie',
    bio: 'Visual artist with a unique perspective on digital creativity.',
    profileImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '32',
    name: 'web300fa',
    slug: 'web300fa',
    bio: 'Digital artist pushing the boundaries of web-based art.',
    profileImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '33',
    name: 'zll_1013575110',
    slug: 'zll_1013575110',
    bio: 'Contemporary artist creating thought-provoking digital works.',
    profileImageUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  // Weekly Features Artists - Memes
  {
    _id: '34',
    name: '0xdivy',
    slug: '0xdivy',
    bio: 'Meme artist bringing humor and creativity to digital spaces.',
    profileImageUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '35',
    name: 'Akka Pa',
    slug: 'akka-pa',
    bio: 'Creative video meme artist with a unique comedic vision.',
    profileImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '36',
    name: 'Its_axios',
    slug: 'its_axios',
    bio: 'Tech-savvy meme creator combining humor with digital artistry.',
    profileImageUrl: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '37',
    name: 'siiiuuperman',
    slug: 'siiiuuperman',
    bio: 'Superhero of memes, creating viral content with style.',
    profileImageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  {
    _id: '38',
    name: 'srikanth',
    slug: 'srikanth',
    bio: 'Video meme artist creating entertaining and engaging content.',
    profileImageUrl: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
  // Weekly Features Artists - GIFs
  {
    _id: '39',
    name: 'feriset',
    slug: 'feriset',
    bio: 'GIF artist creating captivating animated sequences.',
    profileImageUrl: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400&h=400&fit=crop&crop=face',
    status: 'featured',
    createdAt: '2025-09-20',
    updatedAt: '2025-09-28',
  },
];

// Helper function to find artist by filename
function getArtistByFilename(filename: string): Artist {
  const artistName = filename.split('.')[0]; // Remove file extension
  const artist = mockArtists.find(a => a.name === artistName);
  return artist || mockArtists[0]; // Fallback to first artist if not found
}

// Mock Mediums
export const mockMediums: Medium[] = [
  { _id: '1', name: 'Digital Art', slug: 'digital-art' },
  { _id: '2', name: 'Painting', slug: 'painting' },
  { _id: '3', name: 'Photography', slug: 'photography' },
  { _id: '4', name: 'Mixed Media', slug: 'mixed-media' },
  { _id: '5', name: 'Drawing', slug: 'drawing' },
  { _id: '6', name: 'Sculpture', slug: 'sculpture' },
];

// Mock Styles
export const mockStyles: Style[] = [
  { _id: '1', name: 'Abstract', slug: 'abstract' },
  { _id: '2', name: 'Realism', slug: 'realism' },
  { _id: '3', name: 'Impressionism', slug: 'impressionism' },
  { _id: '4', name: 'Contemporary', slug: 'contemporary' },
  { _id: '5', name: 'Minimalism', slug: 'minimalism' },
  { _id: '6', name: 'Pop Art', slug: 'pop-art' },
];

// Mock Themes
export const mockThemes: Theme[] = [
  { _id: '1', name: 'Nature', slug: 'nature', isSuggested: true },
  { _id: '2', name: 'Urban Life', slug: 'urban-life', isSuggested: true },
  { _id: '3', name: 'Human Connection', slug: 'human-connection', isSuggested: false },
  { _id: '4', name: 'Technology', slug: 'technology', isSuggested: true },
  { _id: '5', name: 'Emotions', slug: 'emotions', isSuggested: false },
  { _id: '6', name: 'Identity', slug: 'identity', isSuggested: false },
];

// Mock Events
export const mockEvents: Event[] = [
  {
    _id: '1',
    name: 'Spring Art Festival',
    slug: 'spring-art-festival',
    description: 'Annual celebration of emerging artists and their latest works',
    startDate: '2024-03-01',
    endDate: '2024-03-31',
    isActive: true,
  },
  {
    _id: '2',
    name: 'Digital Dreams Challenge',
    slug: 'digital-dreams-challenge',
    description: 'Exploring the intersection of technology and imagination',
    startDate: '2024-02-01',
    endDate: '2024-02-29',
    isActive: false,
  },
];

// Mock Artworks
export const mockArtworks: Artwork[] = [
  {
    _id: '1',
    title: 'Ethereal Landscapes',
    slug: 'ethereal-landscapes',
    description: 'By arishdona',
    imageUrl: '/Artists/Arts/arishdona.webp',
    artist: getArtistByFilename('arishdona.webp'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[0], mockThemes[4]],
    event: mockEvents[0],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-01',
    publicationDate: '2025-03-02',
    isFeatured: true,
    createdAt: '2025-03-01',
    updatedAt: '2025-03-02',
  },
  {
    _id: '2',
    title: 'Vibrant Reflections',
    slug: 'vibrant-reflections',
    description: 'By itsmeyourvicky',
    imageUrl: '/Artists/Arts/itsmeyourvicky.webp',
    artist: getArtistByFilename('itsmeyourvicky.webp'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[4], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-05',
    publicationDate: '2025-03-06',
    isFeatured: false,
    createdAt: '2025-03-05',
    updatedAt: '2025-03-06',
  },
  {
    _id: '3',
    title: 'Emotional Depths',
    slug: 'emotional-depths',
    description: 'By Phuong',
    imageUrl: '/Artists/Arts/Phuong.webp',
    artist: getArtistByFilename('Phuong.webp'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-10',
    publicationDate: '2025-03-11',
    isFeatured: false,
    createdAt: '2025-03-10',
    updatedAt: '2025-03-11',
  },
  {
    _id: '4',
    title: 'Digital Renaissance',
    slug: 'digital-renaissance',
    description: 'By vadim064',
    imageUrl: '/Artists/Arts/vadim064.webp',
    artist: getArtistByFilename('vadim064.webp'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[4], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-15',
    publicationDate: '2025-03-16',
    isFeatured: false,
    createdAt: '2025-03-15',
    updatedAt: '2025-03-16',
  },
  {
    _id: '5',
    title: 'Crypto Visions',
    slug: 'crypto-visions',
    description: 'By 0xYANDY',
    imageUrl: '/Artists/Arts/0xYANDY.mp4',
    artist: getArtistByFilename('0xYANDY.mp4'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-20',
    publicationDate: '2025-03-21',
    isFeatured: false,
    createdAt: '2025-03-20',
    updatedAt: '2025-03-21',
  },
  {
    _id: '6',
    title: 'Abstract Narratives',
    slug: 'abstract-narratives',
    description: 'By Alexeyya',
    imageUrl: '/Artists/Arts/Alexeyya.mp4',
    artist: getArtistByFilename('Alexeyya.mp4'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-25',
    publicationDate: '2025-03-26',
    isFeatured: false,
    createdAt: '2025-03-25',
    updatedAt: '2025-03-26',
  },
  {
    _id: '7',
    title: 'Digital Alchemy',
    slug: 'digital-alchemy',
    description: 'By Kharather',
    imageUrl: '/Artists/Arts/Kharather.mp4',
    artist: getArtistByFilename('Kharather.mp4'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-22',
    publicationDate: '2025-03-23',
    isFeatured: false,
    createdAt: '2025-03-22',
    updatedAt: '2025-03-23',
  },
  {
    _id: '8',
    title: 'Flowing Serenity',
    slug: 'flowing-serenity',
    description: 'By phuong',
    imageUrl: '/Artists/Arts/phuong.mp4',
    artist: getArtistByFilename('phuong.mp4'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-21',
    publicationDate: '2025-03-22',
    isFeatured: false,
    createdAt: '2025-03-21',
    updatedAt: '2025-03-22',
  },
  {
    _id: '9',
    title: 'Unleashed Energy',
    slug: 'unleashed-energy',
    description: 'By rawrage',
    imageUrl: '/Artists/Arts/rawrage.mp4',
    artist: getArtistByFilename('rawrage.mp4'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[4], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-20',
    publicationDate: '2025-03-21',
    isFeatured: false,
    createdAt: '2025-03-20',
    updatedAt: '2025-03-21',
  },

];

// Mock Memes
export const mockMemes: Artwork[] = [
  {
    _id: 'meme1',
    title: 'Ahmed\'s Art Wisdom',
    slug: 'ahmeds-art-wisdom',
    description: 'By Ahamedzola',
    imageUrl: '/Artists/Memes/Ahamedzola.webp',
    artist: getArtistByFilename('Ahamedzola.webp'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-28',
    publicationDate: '2025-03-29',
    isFeatured: false,
    createdAt: '2025-03-28',
    updatedAt: '2025-03-29',
  },
  {
    _id: 'meme2',
    title: 'Dio\'s Digital Dilemma',
    slug: 'dios-digital-dilemma',
    description: 'By Diokusumo',
    imageUrl: '/Artists/Memes/Diokusumo.webp',
    artist: getArtistByFilename('Diokusumo.webp'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-27',
    publicationDate: '2025-03-28',
    isFeatured: true,
    createdAt: '2025-03-27',
    updatedAt: '2025-03-28',
  },
  {
    _id: 'meme3',
    title: 'Sai\'s Creative Commentary',
    slug: 'sais-creative-commentary',
    description: 'By Nagasaikurma',
    imageUrl: '/Artists/Memes/Nagasaikurma.webp',
    artist: getArtistByFilename('Nagasaikurma.webp'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-26',
    publicationDate: '2025-03-27',
    isFeatured: false,
    createdAt: '2025-03-26',
    updatedAt: '2025-03-27',
  },
  {
    _id: 'meme4',
    title: 'Fartxe\'s Animated Antics',
    slug: 'fartxes-animated-antics',
    description: 'By Fartxe',
    imageUrl: '/Artists/Memes/Fartxe.gif',
    artist: getArtistByFilename('Fartxe.gif'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-25',
    publicationDate: '2025-03-26',
    isFeatured: false,
    createdAt: '2025-03-25',
    updatedAt: '2025-03-26',
  },
  {
    _id: 'meme5',
    title: 'DT Dude\'s Developer Drama',
    slug: 'dt-dudes-developer-drama',
    description: 'By dt-dude',
    imageUrl: '/Artists/Memes/dt-dude.mp4',
    artist: getArtistByFilename('dt-dude.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-24',
    publicationDate: '2025-03-25',
    isFeatured: false,
    createdAt: '2025-03-24',
    updatedAt: '2025-03-25',
  },
  {
    _id: 'meme6',
    title: 'Katohife\'s Client Chronicles',
    slug: 'katohifes-client-chronicles',
    description: 'By Katohife',
    imageUrl: '/Artists/Memes/Katohife.mp4',
    artist: getArtistByFilename('Katohife.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-23',
    publicationDate: '2025-03-24',
    isFeatured: false,
    createdAt: '2025-03-23',
    updatedAt: '2025-03-24',
  },
  {
    _id: 'meme7',
    title: 'Richard\'s Reality Check',
    slug: 'richards-reality-check',
    description: 'By Richard12',
    imageUrl: '/Artists/Memes/Richard12.mp4',
    artist: getArtistByFilename('Richard12.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-22',
    publicationDate: '2025-03-23',
    isFeatured: false,
    createdAt: '2025-03-22',
    updatedAt: '2025-03-23',
  },
  // Weekly Featured Memes (now permanent in main memes gallery)
  {
    _id: 'meme8',
    title: 'Digital Humor',
    slug: 'digital-humor-0xdivy',
    description: 'By 0xdivy',
    imageUrl: '/Artists/Weekly Features/Memes/0xdivy.webp',
    artist: mockArtists.find(a => a.name === '0xdivy') || mockArtists[0],
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'meme9',
    title: 'Animated Comedy',
    slug: 'animated-comedy-0xdivy2',
    description: 'By 0xdivy',
    imageUrl: '/Artists/Weekly Features/Memes/0xdivy2.gif',
    artist: mockArtists.find(a => a.name === '0xdivy') || mockArtists[0],
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'meme10',
    title: 'Video Meme Magic',
    slug: 'video-meme-magic-akka-pa',
    description: 'By Akka Pa',
    imageUrl: '/Artists/Weekly Features/Memes/Akka Pa.mp4',
    artist: mockArtists.find(a => a.name === 'Akka Pa') || mockArtists[0],
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'meme11',
    title: 'Tech Humor',
    slug: 'tech-humor-its-axios',
    description: 'By Its_axios',
    imageUrl: '/Artists/Weekly Features/Memes/Its_axios.mp4',
    artist: mockArtists.find(a => a.name === 'Its_axios') || mockArtists[0],
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'meme12',
    title: 'Super Meme',
    slug: 'super-meme-siiiuuperman',
    description: 'By siiiuuperman',
    imageUrl: '/Artists/Weekly Features/Memes/siiiuuperman.webp',
    artist: mockArtists.find(a => a.name === 'siiiuuperman') || mockArtists[0],
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'meme13',
    title: 'Creative Comedy',
    slug: 'creative-comedy-srikanth',
    description: 'By srikanth',
    imageUrl: '/Artists/Weekly Features/Memes/srikanth.mp4',
    artist: mockArtists.find(a => a.name === 'srikanth') || mockArtists[0],
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-28',
    updatedAt: '2025-09-28',
  },
];

// Mock GIFs
export const mockGifs: Artwork[] = [
  {
    _id: 'gif1',
    title: 'Golden Spiral Dreams',
    slug: 'golden-spiral-dreams',
    description: 'By AlexGoldPack',
    imageUrl: '/Artists/Gifs/AlexGoldPack.gif',
    artist: getArtistByFilename('AlexGoldPack.gif'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-30',
    publicationDate: '2025-03-31',
    isFeatured: true,
    createdAt: '2025-03-30',
    updatedAt: '2025-03-31',
  },
  {
    _id: 'gif2',
    title: 'Geometric Metamorphosis',
    slug: 'geometric-metamorphosis',
    description: 'By Grejk',
    imageUrl: '/Artists/Gifs/Grejk.gif',
    artist: getArtistByFilename('Grejk.gif'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-29',
    publicationDate: '2025-03-30',
    isFeatured: false,
    createdAt: '2025-03-29',
    updatedAt: '2025-03-30',
  },
  {
    _id: 'gif3',
    title: 'Digital Waterways',
    slug: 'digital-waterways',
    description: 'By johnathanhnd',
    imageUrl: '/Artists/Gifs/johnathanhnd.gif',
    artist: getArtistByFilename('johnathanhnd.gif'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-28',
    publicationDate: '2025-03-29',
    isFeatured: false,
    createdAt: '2025-03-28',
    updatedAt: '2025-03-29',
  },
  {
    _id: 'gif4',
    title: 'Organic Rhythms',
    slug: 'organic-rhythms',
    description: 'By Kaygon',
    imageUrl: '/Artists/Gifs/Kaygon.gif',
    artist: getArtistByFilename('Kaygon.gif'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-27',
    publicationDate: '2025-03-28',
    isFeatured: false,
    createdAt: '2025-03-27',
    updatedAt: '2025-03-28',
  },
  {
    _id: 'gif5',
    title: 'Fluid Consciousness',
    slug: 'fluid-consciousness',
    description: 'By minhhnob',
    imageUrl: '/Artists/Gifs/minhhnob.gif',
    artist: getArtistByFilename('minhhnob.gif'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[4], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-26',
    publicationDate: '2025-03-27',
    isFeatured: false,
    createdAt: '2025-03-26',
    updatedAt: '2025-03-27',
  },
  {
    _id: 'gif6',
    title: 'Enigmatic Transformations',
    slug: 'enigmatic-transformations',
    description: 'By Misterche',
    imageUrl: '/Artists/Gifs/Misterche.gif',
    artist: getArtistByFilename('Misterche.gif'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-25',
    publicationDate: '2025-03-26',
    isFeatured: false,
    createdAt: '2025-03-25',
    updatedAt: '2025-03-26',
  },
  {
    _id: 'gif7',
    title: 'Evolutionary Pulse',
    slug: 'evolutionary-pulse',
    description: 'By newera3',
    imageUrl: '/Artists/Gifs/newera3.gif',
    artist: getArtistByFilename('newera3.gif'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-24',
    publicationDate: '2025-03-25',
    isFeatured: false,
    createdAt: '2025-03-24',
    updatedAt: '2025-03-25',
  },
  {
    _id: 'gif8',
    title: 'Cozy Digital Spaces',
    slug: 'cozy-digital-spaces',
    description: 'By Nook38',
    imageUrl: '/Artists/Gifs/Nook38.gif',
    artist: getArtistByFilename('Nook38.gif'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-23',
    publicationDate: '2025-03-24',
    isFeatured: false,
    createdAt: '2025-03-23',
    updatedAt: '2025-03-24',
  },
  {
    _id: 'gif9',
    title: 'Rhythmic Patterns',
    slug: 'rhythmic-patterns',
    description: 'By ricky1414',
    imageUrl: '/Artists/Gifs/ricky1414.gif',
    artist: getArtistByFilename('ricky1414.gif'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-22',
    publicationDate: '2025-03-23',
    isFeatured: false,
    createdAt: '2025-03-22',
    updatedAt: '2025-03-23',
  },
  {
    _id: 'gif10',
    title: 'Dynamic Synthesis',
    slug: 'dynamic-synthesis',
    description: 'By Bikoy',
    imageUrl: '/Artists/Gifs/Bikoy.mp4',
    artist: getArtistByFilename('Bikoy.mp4'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-21',
    publicationDate: '2025-03-22',
    isFeatured: false,
    createdAt: '2025-03-21',
    updatedAt: '2025-03-22',
  },
  // Weekly Featured GIF (now permanent in main gifs gallery)
  {
    _id: 'gif11',
    title: 'Animated Creation',
    slug: 'animated-creation-feriset',
    description: 'By feriset',
    imageUrl: '/Artists/Weekly Features/Gifs/feriset.gif',
    artist: getArtistByFilename('feriset.gif'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
];

// Weekly featured artworks are now in the main mockArtworks array with isFeatured: true

// Weekly featured memes are now in the main mockMemes array with isFeatured: true

// Weekly featured GIFs are now in the main mockGifs array with isFeatured: true

// Mock Weekly Features
export const mockWeeklyFeatures: WeeklyFeature[] = [
  {
    _id: '1',
    title: 'Artist Spotlight: Maya Chen',
    slug: 'maya-chen-spotlight',
    artist: mockArtists[0],
    featuredArtworks: [mockArtworks[0], mockArtworks[3]],
    introduction: 'This week, we\'re thrilled to spotlight Maya Chen, a visionary digital artist whose work seamlessly blends technology with human emotion. Maya\'s pieces invite viewers into immersive digital landscapes that challenge our perception of reality.',
    artistNoteQuote: 'I believe art should be a bridge between the digital and physical worlds. My work explores how technology can enhance rather than replace human connection.',
    scheduledDate: '2024-03-18',
    publicationStatus: 'published',
    publishedAt: '2024-03-18',
    createdBy: {
      _id: 'admin1',
      username: 'curator',
      email: 'curator@riallery.com',
      role: 'curator',
      isActive: true,
      createdAt: '2024-01-01',
      updatedAt: '2024-03-01',
    },
    updatedBy: {
      _id: 'admin1',
      username: 'curator',
      email: 'curator@riallery.com',
      role: 'curator',
      isActive: true,
      createdAt: '2024-01-01',
      updatedAt: '2024-03-01',
    },
    createdAt: '2024-03-15',
    updatedAt: '2024-03-18',
  },
  {
    _id: '2',
    title: 'Artist Spotlight: Alex Rivera',
    slug: 'alex-rivera-spotlight',
    artist: mockArtists[1],
    featuredArtworks: [mockArtworks[1], mockArtworks[4]],
    introduction: 'Alex Rivera brings the pulse of urban life to canvas with bold, abstract compositions that capture the energy of modern cities. Their work reflects the constant motion and vibrant spirit of contemporary urban experience.',
    artistNoteQuote: 'Cities are living, breathing entities with their own rhythm and energy. I try to capture that pulse and translate it into something visual and emotional.',
    scheduledDate: '2024-03-11',
    publicationStatus: 'archived',
    publishedAt: '2024-03-11',
    archivedAt: '2024-03-18',
    createdBy: {
      _id: 'admin1',
      username: 'curator',
      email: 'curator@riallery.com',
      role: 'curator',
      isActive: true,
      createdAt: '2024-01-01',
      updatedAt: '2024-03-01',
    },
    updatedBy: {
      _id: 'admin1',
      username: 'curator',
      email: 'curator@riallery.com',
      role: 'curator',
      isActive: true,
      createdAt: '2024-01-01',
      updatedAt: '2024-03-01',
    },
    createdAt: '2024-03-08',
    updatedAt: '2024-03-18',
  },
];

// Mock API functions for development
export function getMockArtworks(page: number = 1, limit: number = 12) {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedArtworks = mockArtworks.slice(startIndex, endIndex);
  
  return {
    artworks: paginatedArtworks,
    total: mockArtworks.length,
    page,
    limit,
    hasMore: endIndex < mockArtworks.length,
  };
}

export function getMockArtworkBySlug(slug: string) {
  return mockArtworks.find(artwork => artwork.slug === slug) || null;
}

export function getMockFeatures() {
  return mockWeeklyFeatures;
}

export function getMockFeatureBySlug(slug: string) {
  return mockWeeklyFeatures.find(feature => feature.slug === slug) || null;
}

export function getMockCurrentFeature() {
  return mockWeeklyFeatures.find(feature => feature.publicationStatus === 'published') || null;
}

export function getMockMemes(page: number = 1, limit: number = 12) {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedMemes = mockMemes.slice(startIndex, endIndex);
  
  return {
    artworks: paginatedMemes,
    total: mockMemes.length,
    page,
    limit,
    hasMore: endIndex < mockMemes.length,
  };
}

export function getMockMemeBySlug(slug: string) {
  return mockMemes.find(meme => meme.slug === slug) || null;
}

export function getMockGifs(page: number = 1, limit: number = 12) {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedGifs = mockGifs.slice(startIndex, endIndex);
  
  return {
    artworks: paginatedGifs,
    total: mockGifs.length,
    page,
    limit,
    hasMore: endIndex < mockGifs.length,
  };
}

export function getMockGifBySlug(slug: string) {
  return mockGifs.find(gif => gif.slug === slug) || null;
}

export function getMockWeeklyFeaturedArtworks() {
  // Return the weekly featured artworks from the main mockArtworks array
  return mockArtworks.filter(artwork => artwork.isFeatured && artwork.yearCreated === 2025);
}

export function getMockWeeklyFeaturedMemes() {
  // Return the weekly featured memes from the main mockMemes array
  return mockMemes.filter(meme => meme.isFeatured && meme.yearCreated === 2025);
}

export function getMockWeeklyFeaturedGifs() {
  // Return the weekly featured GIFs from the main mockGifs array
  return mockGifs.filter(gif => gif.isFeatured && gif.yearCreated === 2025);
}