import { Artwork, Artist, Medium, Style, Theme, Event, WeeklyFeature, User } from '@/types';

// Mock themes
export const mockThemes: Theme[] = [
  { _id: '1', name: 'Abstract', slug: 'abstract', isSuggested: true },
  { _id: '2', name: 'Portrait', slug: 'portrait', isSuggested: true },
  { _id: '3', name: 'Landscape', slug: 'landscape', isSuggested: true },
  { _id: '4', name: 'Digital', slug: 'digital', isSuggested: true },
  { _id: '5', name: 'Contemporary', slug: 'contemporary', isSuggested: true },
  { _id: '6', name: 'Humor', slug: 'humor', isSuggested: true },
];

// Mock mediums
export const mockMediums: Medium[] = [
  { _id: '1', name: 'Digital Art', slug: 'digital-art' },
  { _id: '2', name: 'Oil Paint', slug: 'oil-paint' },
  { _id: '3', name: 'Acrylic Paint', slug: 'acrylic-paint' },
  { _id: '4', name: 'Watercolor', slug: 'watercolor' },
  { _id: '5', name: 'Mixed Media', slug: 'mixed-media' },
];

// Mock styles
export const mockStyles: Style[] = [
  { _id: '1', name: 'Realistic', slug: 'realistic' },
  { _id: '2', name: 'Impressionist', slug: 'impressionist' },
  { _id: '3', name: 'Surreal', slug: 'surreal' },
  { _id: '4', name: 'Minimalist', slug: 'minimalist' },
  { _id: '5', name: 'Pop Art', slug: 'pop-art' },
  { _id: '6', name: 'Meme', slug: 'meme' },
];

// Mock events
export const mockEvents: Event[] = [
  {
    _id: '1',
    name: 'Spring Art Festival',
    slug: 'spring-art-festival',
    description: 'Annual celebration of emerging artists and their latest works',
    startDate: '2024-03-01',
    endDate: '2024-03-31',
    isActive: true,
  },
  {
    _id: '2',
    name: 'Digital Dreams Challenge',
    slug: 'digital-dreams-challenge',
    description: 'Monthly challenge for digital artists to showcase their creativity',
    startDate: '2024-02-01',
    endDate: '2024-02-29',
    isActive: false,
  },
  {
    _id: '3',
    name: 'Summer Showcase',
    slug: 'summer-showcase',
    description: 'Community showcase featuring the best summer-themed artworks',
    startDate: '2024-06-01',
    endDate: '2024-08-31',
    isActive: true,
  },
];

// Helper function to create artist based on filename
function getArtistByFilename(filename: string): Artist {
  const nameWithoutExt = filename.replace(/\.[^/.]+$/, '');
  const artistName = nameWithoutExt.replace(/[_-]/g, ' ');
  
  return {
    _id: `artist-${nameWithoutExt}`,
    name: artistName,
    slug: nameWithoutExt.toLowerCase(),
    bio: `Creative artist specializing in digital art and visual storytelling.`,
    status: 'active',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  };
}

// Mock artists (main gallery artists)
export const mockArtists: Artist[] = [
  {
    _id: '1',
    name: 'Ahamedzola',
    slug: 'ahamedzola',
    bio: 'Contemporary digital artist known for thought-provoking visual narratives.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '2', 
    name: 'Diokusumo',
    slug: 'diokusumo',
    bio: 'Digital artist creating vibrant and expressive contemporary works.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '3',
    name: 'Nagasaikurma',
    slug: 'nagasaikurma',
    bio: 'Visual storyteller combining traditional themes with modern digital techniques.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '4',
    name: 'Fartxe',
    slug: 'fartxe',
    bio: 'Innovative animator creating engaging visual experiences.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '5',
    name: 'dt-dude',
    slug: 'dt-dude',
    bio: 'Tech-inspired artist creating content that bridges technology and creativity.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '6',
    name: 'Siiiuuper',
    slug: 'siiiuuper',
    bio: 'Dynamic artist known for energetic and vibrant creative expressions.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '7',
    name: 'Sukafunk',
    slug: 'sukafunk',
    bio: 'Multi-media artist exploring the intersection of music and visual art.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '8',
    name: 'NVRL',
    slug: 'nvrl',
    bio: 'Contemporary artist pushing boundaries with innovative digital techniques.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '9',
    name: 'Neulpum',
    slug: 'neulpum',
    bio: 'Minimalist artist creating clean and impactful visual compositions.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
];

// Mock artworks (main gallery - original content only)
export const mockArtworks: Artwork[] = [
  // Previous Weekly Features (rotated out - now in Recent Artworks)
  {
    _id: 'prev-weekly-art1',
    title: 'Heaven\'s Previous Feature',
    slug: 'previous-heavens-feature',
    description: 'Former weekly featured artwork by heaven',
    imageUrl: '/Artists/Weekly Features/Arts/heaven.webp',
    artist: getArtistByFilename('heaven'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-15',
    publicationDate: '2025-09-20',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-20',
    createdAt: '2025-09-15',
    updatedAt: '2025-09-20',
  },
  {
    _id: 'prev-weekly-art2',
    title: 'Simmu\'s Previous Feature',
    slug: 'previous-simmus-feature',
    description: 'Former weekly featured artwork by simmu',
    imageUrl: '/Artists/Weekly Features/Arts/simmu.webp',
    artist: getArtistByFilename('simmu'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-10',
    publicationDate: '2025-09-15',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-15',
    createdAt: '2025-09-10',
    updatedAt: '2025-09-15',
  },
  {
    _id: 'prev-weekly-art3',
    title: 'Ticotico\'s Previous Feature',
    slug: 'previous-ticoticos-feature',
    description: 'Former weekly featured artwork by ticotico',
    imageUrl: '/Artists/Weekly Features/Arts/ticotico.webp',
    artist: getArtistByFilename('ticotico'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-05',
    publicationDate: '2025-09-10',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-10',
    createdAt: '2025-09-05',
    updatedAt: '2025-09-10',
  },
  {
    _id: 'prev-weekly-art4',
    title: 'Saidulhaque\'s Previous Feature',
    slug: 'previous-saidulhaques-feature',
    description: 'Former weekly featured artwork by saidulhaque',
    imageUrl: '/Artists/Weekly Features/Arts/saidulhaque.webp',
    artist: getArtistByFilename('saidulhaque'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-08-25',
    publicationDate: '2025-08-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-08-30',
    createdAt: '2025-08-25',
    updatedAt: '2025-08-30',
  },
  {
    _id: 'prev-weekly-art5',
    title: 'Weisjumm\'s Previous Feature',
    slug: 'previous-weisjumms-feature',
    description: 'Former weekly featured artwork by weisjumm',
    imageUrl: '/Artists/Weekly Features/Arts/weisjumm.webp',
    artist: getArtistByFilename('weisjumm'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-08-20',
    publicationDate: '2025-08-25',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-08-25',
    createdAt: '2025-08-20',
    updatedAt: '2025-08-25',
  },
  
  // Regular artworks (non-featured content)
  {
    _id: 'art1',
    title: 'Digital Serenity',
    slug: 'digital-serenity',
    description: 'By arishdona',
    imageUrl: '/Artists/Arts/arishdona.webp',
    artist: getArtistByFilename('arishdona.webp'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-15',
    publicationDate: '2025-03-18',
    isFeatured: true,
    createdAt: '2025-03-15',
    updatedAt: '2025-03-18',
  },
  {
    _id: 'art2',
    title: 'Contemporary Expression',
    slug: 'contemporary-expression',
    description: 'By itsmeyourvicky',
    imageUrl: '/Artists/Arts/itsmeyourvicky.webp',
    artist: getArtistByFilename('itsmeyourvicky.webp'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-14',
    publicationDate: '2025-03-17',
    isFeatured: false,
    createdAt: '2025-03-14',
    updatedAt: '2025-03-17',
  },
  {
    _id: 'art3',
    title: 'Vadim\'s Vision',
    slug: 'vadims-vision',
    description: 'By vadim064',
    imageUrl: '/Artists/Arts/vadim064.webp',
    artist: getArtistByFilename('vadim064.webp'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-13',
    publicationDate: '2025-03-16',
    isFeatured: false,
    createdAt: '2025-03-13',
    updatedAt: '2025-03-16',
  },
  {
    _id: 'art4',
    title: 'Animated Artistry',
    slug: 'animated-artistry',
    description: 'By 0xYANDY',
    imageUrl: '/Artists/Arts/0xYANDY.mp4',
    artist: getArtistByFilename('0xYANDY.mp4'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-12',
    publicationDate: '2025-03-15',
    isFeatured: true,
    createdAt: '2025-03-12',
    updatedAt: '2025-03-15',
  },
  {
    _id: 'art5',
    title: 'Dynamic Movement',
    slug: 'dynamic-movement',
    description: 'By Alexeyya',
    imageUrl: '/Artists/Arts/Alexeyya.mp4',
    artist: getArtistByFilename('Alexeyya.mp4'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-11',
    publicationDate: '2025-03-14',
    isFeatured: false,
    createdAt: '2025-03-11',
    updatedAt: '2025-03-14',
  },
  {
    _id: 'art6',
    title: 'Phuong Expression',
    slug: 'phuong-expression',
    description: 'By Phuong',
    imageUrl: '/Artists/Arts/Phuong.webp',
    artist: getArtistByFilename('Phuong.webp'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-10',
    publicationDate: '2025-03-13',
    isFeatured: false,
    createdAt: '2025-03-10',
    updatedAt: '2025-03-13',
  },
  {
    _id: 'art7',
    title: 'Raw Rage',
    slug: 'raw-rage',
    description: 'By rawrage',
    imageUrl: '/Artists/Arts/rawrage.mp4',
    artist: getArtistByFilename('rawrage.mp4'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-09',
    publicationDate: '2025-03-12',
    isFeatured: false,
    createdAt: '2025-03-09',
    updatedAt: '2025-03-12',
  },
  {
    _id: 'art8',
    title: 'Kharather Vision',
    slug: 'kharather-vision',
    description: 'By Kharather',
    imageUrl: '/Artists/Arts/Kharather.mp4',
    artist: getArtistByFilename('Kharather.mp4'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-08',
    publicationDate: '2025-03-11',
    isFeatured: false,
    createdAt: '2025-03-08',
    updatedAt: '2025-03-11',
  },
  {
    _id: 'art9',
    title: 'Phuong\'s Elegance',
    slug: 'phuongs-elegance',
    description: 'By phuong',
    imageUrl: '/Artists/Arts/phuong.mp4',
    artist: getArtistByFilename('phuong.mp4'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-07',
    publicationDate: '2025-03-10',
    isFeatured: false,
    createdAt: '2025-03-07',
    updatedAt: '2025-03-10',
  },
  // Weekly Featured Artworks (with flag for preservation when features rotate)
  {
    _id: 'weekly-art1',
    title: 'Ceqih\'s Creative Vision',
    slug: 'weekly-creative-vision-ceqih',
    description: 'By ceqih',
    imageUrl: '/Artists/Weekly Features/Arts/ceqih.jpg',
    artist: getArtistByFilename('ceqih'),
    medium: mockMediums[1],
    style: mockStyles[0],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art2',
    title: 'Ciao\'s Digital Masterpiece',
    slug: 'weekly-digital-masterpiece-ciao0910',
    description: 'By ciao0910',
    imageUrl: '/Artists/Weekly Features/Arts/ciao0910.webp',
    artist: getArtistByFilename('ciao0910'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art3',
    title: 'Darkthgink\'s Dark Vision',
    slug: 'weekly-dark-vision-darkthgink',
    description: 'By darkthgink',
    imageUrl: '/Artists/Weekly Features/Arts/darkthgink.webp',
    artist: getArtistByFilename('darkthgink'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art4',
    title: 'Dldw1314\'s Creative Expression',
    slug: 'weekly-creative-expression-dldw1314',
    description: 'By dldw1314',
    imageUrl: '/Artists/Weekly Features/Arts/dldw1314.webp',
    artist: getArtistByFilename('dldw1314'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art5',
    title: 'Hrx0005\'s Artistic Journey',
    slug: 'weekly-artistic-journey-hrx0005',
    description: 'By hrx0005',
    imageUrl: '/Artists/Weekly Features/Arts/hrx0005.webp',
    artist: getArtistByFilename('hrx0005'),
    medium: mockMediums[2],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art6',
    title: 'Jdr525\'s Digital Art',
    slug: 'weekly-digital-art-jdr525',
    description: 'By jdr525',
    imageUrl: '/Artists/Weekly Features/Arts/jdr525.webp',
    artist: getArtistByFilename('jdr525'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art7',
    title: 'Lueguo\'s Video Creation',
    slug: 'weekly-video-creation-lueguo',
    description: 'By lueguo',
    imageUrl: '/Artists/Weekly Features/Arts/lueguo.mp4',
    artist: getArtistByFilename('lueguo'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art8',
    title: 'Lueguo\'s Static Art',
    slug: 'weekly-static-art-lueguo',
    description: 'By lueguo',
    imageUrl: '/Artists/Weekly Features/Arts/lueguo.webp',
    artist: getArtistByFilename('lueguo'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art9',
    title: 'May821\'s Video Art',
    slug: 'weekly-video-art-may821',
    description: 'By may821',
    imageUrl: '/Artists/Weekly Features/Arts/may821.mp4',
    artist: getArtistByFilename('may821'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art10',
    title: 'Novanguyen2802\'s Masterpiece',
    slug: 'weekly-masterpiece-novanguyen2802',
    description: 'By novanguyen2802',
    imageUrl: '/Artists/Weekly Features/Arts/novanguyen2802.webp',
    artist: getArtistByFilename('novanguyen2802'),
    medium: mockMediums[2],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art11',
    title: 'Tinkyviki\'s Creative Vision',
    slug: 'weekly-creative-vision-tinkyviki',
    description: 'By tinkyviki',
    imageUrl: '/Artists/Weekly Features/Arts/tinkyviki.webp',
    artist: getArtistByFilename('tinkyviki'),
    medium: mockMediums[1],
    style: mockStyles[0],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art-new1',
    title: 'Adii_fx\'s Moving Art',
    slug: 'weekly-moving-art-adii-fx',
    description: 'By adii_fx',
    imageUrl: '/Artists/Weekly Features/Arts/adii_fx.mov',
    artist: getArtistByFilename('adii_fx'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'weekly-art-new2',
    title: 'Bas_baster\'s Video Creation',
    slug: 'weekly-video-creation-bas-baster',
    description: 'By bas_baster',
    imageUrl: '/Artists/Weekly Features/Arts/bas_baster.mp4',
    artist: getArtistByFilename('bas_baster'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'art-new1',
    title: 'Batuhantkmk\'s Creation',
    slug: 'batuhantkmks-creation',
    description: 'By batuhantkmk',
    imageUrl: '/Artists/Arts/batuhantkmk.mp4',
    artist: getArtistByFilename('batuhantkmk'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'art-new2',
    title: 'Haruvip\'s Digital Art',
    slug: 'haruvips-digital-art',
    description: 'By haruvip',
    imageUrl: '/Artists/Arts/haruvip.webp',
    artist: getArtistByFilename('haruvip'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'art-new3',
    title: 'Himu_xyz\'s Video Art',
    slug: 'himu-xyz-video-art',
    description: 'By himu_xyz',
    imageUrl: '/Artists/Arts/himu_xyz.mp4',
    artist: getArtistByFilename('himu_xyz'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'art-new4',
    title: 'Lika_enigma\'s Enigmatic Video',
    slug: 'lika-enigma-enigmatic-video',
    description: 'By lika_enigma',
    imageUrl: '/Artists/Arts/lika_enigma.mp4',
    artist: getArtistByFilename('lika_enigma'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'art-new5',
    title: 'Remwasdie\'s Art',
    slug: 'remwasdies-art',
    description: 'By remwasdie',
    imageUrl: '/Artists/Arts/remwasdie.webp',
    artist: getArtistByFilename('remwasdie'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'art-new6',
    title: 'Web300fa\'s Digital Creation',
    slug: 'web300fas-digital-creation',
    description: 'By web300fa',
    imageUrl: '/Artists/Arts/web300fa.webp',
    artist: getArtistByFilename('web300fa'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'art-new7',
    title: 'Zll_1013575110\'s Art',
    slug: 'zll-1013575110-art',
    description: 'By zll_1013575110',
    imageUrl: '/Artists/Arts/zll_1013575110.webp',
    artist: getArtistByFilename('zll_1013575110'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'art-new8',
    title: 'Cuongquoc\'s Unique Creation',
    slug: 'cuongquoc-unique-creation',
    description: 'By cuongquoc',
    imageUrl: '/Artists/Arts/.cuongquoc',
    artist: getArtistByFilename('cuongquoc'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing1',
    title: 'Kaisar13\'s Weekly Feature',
    slug: 'weekly-feature-kaisar13',
    description: 'By .kaisar13',
    imageUrl: '/Artists/Weekly Features/Arts/.kaisar13.webp',
    artist: getArtistByFilename('kaisar13'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing2',
    title: 'Bankizee\'s Creative Work',
    slug: 'weekly-creative-work-bankizee',
    description: 'By bankizee',
    imageUrl: '/Artists/Weekly Features/Arts/bankizee.webp',
    artist: getArtistByFilename('bankizee'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing3',
    title: 'Baont7294\'s Art Piece',
    slug: 'weekly-art-piece-baont7294',
    description: 'By baont7294',
    imageUrl: '/Artists/Weekly Features/Arts/baont7294.webp',
    artist: getArtistByFilename('baont7294'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[2], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing4',
    title: 'Cryptocaicai\'s Digital Creation',
    slug: 'weekly-digital-creation-cryptocaicai',
    description: 'By cryptocaicai',
    imageUrl: '/Artists/Weekly Features/Arts/cryptocaicai.webp',
    artist: getArtistByFilename('cryptocaicai'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing5',
    title: 'Dongxue999\'s Artistic Vision',
    slug: 'weekly-artistic-vision-dongxue999',
    description: 'By dongxue999',
    imageUrl: '/Artists/Weekly Features/Arts/dongxue999.webp',
    artist: getArtistByFilename('dongxue999'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing6',
    title: 'Emmidaisy\'s Daisy Art',
    slug: 'weekly-daisy-art-emmidaisy',
    description: 'By emmidaisy',
    imageUrl: '/Artists/Weekly Features/Arts/emmidaisy.webp',
    artist: getArtistByFilename('emmidaisy'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing7',
    title: 'Gojekaka\'s Digital Vision',
    slug: 'weekly-digital-vision-gojekaka',
    description: 'By gojekaka',
    imageUrl: '/Artists/Weekly Features/Arts/gojekaka.webp',
    artist: getArtistByFilename('gojekaka'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing8',
    title: 'Hkhf777\'s Creative Expression',
    slug: 'weekly-creative-expression-hkhf777',
    description: 'By hkhf777',
    imageUrl: '/Artists/Weekly Features/Arts/hkhf777.webp',
    artist: getArtistByFilename('hkhf777'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing9',
    title: 'Hoangnhat2_30139\'s Art',
    slug: 'weekly-art-hoangnhat2-30139',
    description: 'By hoangnhat2_30139',
    imageUrl: '/Artists/Weekly Features/Arts/hoangnhat2_30139.webp',
    artist: getArtistByFilename('hoangnhat2_30139'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing10',
    title: 'J.jeth\'s Digital Art',
    slug: 'weekly-digital-art-j-jeth',
    description: 'By j.jeth',
    imageUrl: '/Artists/Weekly Features/Arts/j.jeth.webp',
    artist: getArtistByFilename('j.jeth'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing11',
    title: 'Jamesnanox\'s Creation',
    slug: 'weekly-creation-jamesnanox',
    description: 'By jamesnanox',
    imageUrl: '/Artists/Weekly Features/Arts/jamesnanox.webp',
    artist: getArtistByFilename('jamesnanox'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing12',
    title: 'Kitoccrypto\'s Crypto Art',
    slug: 'weekly-crypto-art-kitoccrypto',
    description: 'By kitoccrypto',
    imageUrl: '/Artists/Weekly Features/Arts/kitoccrypto.webp',
    artist: getArtistByFilename('kitoccrypto'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing13',
    title: 'Kristina.eth\'s Ethereum Art',
    slug: 'weekly-ethereum-art-kristina-eth',
    description: 'By kristina.eth',
    imageUrl: '/Artists/Weekly Features/Arts/kristina.eth.webp',
    artist: getArtistByFilename('kristina.eth'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing14',
    title: 'Laohac234\'s Artistic Work',
    slug: 'weekly-artistic-work-laohac234',
    description: 'By laohac234',
    imageUrl: '/Artists/Weekly Features/Arts/laohac234.webp',
    artist: getArtistByFilename('laohac234'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[0], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing15',
    title: 'Lastexamdoteth\'s Final Art',
    slug: 'weekly-final-art-lastexamdoteth',
    description: 'By lastexamdoteth',
    imageUrl: '/Artists/Weekly Features/Arts/lastexamdoteth.webp',
    artist: getArtistByFilename('lastexamdoteth'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing16',
    title: 'Lucky234294\'s Lucky Art',
    slug: 'weekly-lucky-art-lucky234294',
    description: 'By lucky234294',
    imageUrl: '/Artists/Weekly Features/Arts/lucky234294.webp',
    artist: getArtistByFilename('lucky234294'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing17',
    title: 'Melanthaia\'s Mystical Art',
    slug: 'weekly-mystical-art-melanthaia',
    description: 'By melanthaia',
    imageUrl: '/Artists/Weekly Features/Arts/melanthaia.webp',
    artist: getArtistByFilename('melanthaia'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing18',
    title: 'Moondatdust\'s Cosmic Art',
    slug: 'weekly-cosmic-art-moondatdust',
    description: 'By moondatdust',
    imageUrl: '/Artists/Weekly Features/Arts/moondatdust.webp',
    artist: getArtistByFilename('moondatdust'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing19',
    title: 'Moondatdust\'s Second Cosmic Art',
    slug: 'weekly-second-cosmic-art-moondatdust',
    description: 'By moondatdust',
    imageUrl: '/Artists/Weekly Features/Arts/moondatdust 1.webp',
    artist: getArtistByFilename('moondatdust'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing20',
    title: 'Norektguy\'s No Rekt Art',
    slug: 'weekly-no-rekt-art-norektguy',
    description: 'By norektguy',
    imageUrl: '/Artists/Weekly Features/Arts/norektguy.webp',
    artist: getArtistByFilename('norektguy'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing21',
    title: 'Ntv54\'s Technical Vision',
    slug: 'weekly-technical-vision-ntv54',
    description: 'By ntv54',
    imageUrl: '/Artists/Weekly Features/Arts/ntv54.webp',
    artist: getArtistByFilename('ntv54'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing22',
    title: 'Only1coziii\'s Unique Creation',
    slug: 'weekly-unique-creation-only1coziii',
    description: 'By only1coziii',
    imageUrl: '/Artists/Weekly Features/Arts/only1coziii.webp',
    artist: getArtistByFilename('only1coziii'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing23',
    title: 'Paradise.0406\'s Tropical Vision',
    slug: 'weekly-tropical-vision-paradise0406',
    description: 'By paradise.0406',
    imageUrl: '/Artists/Weekly Features/Arts/paradise.0406.webp',
    artist: getArtistByFilename('paradise.0406'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing24',
    title: 'Pauline Fatima\'s Expression',
    slug: 'weekly-expression-pauline-fatima',
    description: 'By Pauline fatima',
    imageUrl: '/Artists/Weekly Features/Arts/Pauline fatima.webp',
    artist: getArtistByFilename('Pauline fatima'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing25',
    title: 'Saenqo\'s Serenity',
    slug: 'weekly-serenity-saenqo',
    description: 'By saenqo',
    imageUrl: '/Artists/Weekly Features/Arts/saenqo.webp',
    artist: getArtistByFilename('saenqo'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing26',
    title: 'Samuraikai1\'s Warrior Spirit',
    slug: 'weekly-warrior-spirit-samuraikai1',
    description: 'By samuraikai1',
    imageUrl: '/Artists/Weekly Features/Arts/samuraikai1.webp',
    artist: getArtistByFilename('samuraikai1'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[2], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing27',
    title: 'Second_______\'s Minimalist Work',
    slug: 'weekly-minimalist-work-second',
    description: 'By second_______',
    imageUrl: '/Artists/Weekly Features/Arts/second_______.webp',
    artist: getArtistByFilename('second_______'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[1]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing28',
    title: 'Shabby869\'s Rustic Art',
    slug: 'weekly-rustic-art-shabby869',
    description: 'By shabby869',
    imageUrl: '/Artists/Weekly Features/Arts/shabby869.webp',
    artist: getArtistByFilename('shabby869'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing29',
    title: 'Tigrebr4nco\'s Tiger Art',
    slug: 'weekly-tiger-art-tigrebr4nco',
    description: 'By tigrebr4nco',
    imageUrl: '/Artists/Weekly Features/Arts/tigrebr4nco.webp',
    artist: getArtistByFilename('tigrebr4nco'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing30',
    title: 'Uzunkuyruk\'s Long Tail Art',
    slug: 'weekly-long-tail-art-uzunkuyruk',
    description: 'By uzunkuyruk',
    imageUrl: '/Artists/Weekly Features/Arts/uzunkuyruk.webp',
    artist: getArtistByFilename('uzunkuyruk'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing31',
    title: 'Viktorsangre\'s Blood Art',
    slug: 'weekly-blood-art-viktorsangre',
    description: 'By viktorsangre',
    imageUrl: '/Artists/Weekly Features/Arts/viktorsangre.webp',
    artist: getArtistByFilename('viktorsangre'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing32',
    title: 'Web3_joker\'s Digital Comedy',
    slug: 'weekly-digital-comedy-web3-joker',
    description: 'By web3_joker',
    imageUrl: '/Artists/Weekly Features/Arts/web3_joker.webp',
    artist: getArtistByFilename('web3_joker'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'weekly-art-missing33',
    title: '_bettermee\'s Self Improvement Art',
    slug: 'weekly-self-improvement-art-bettermee',
    description: 'By _bettermee',
    imageUrl: '/Artists/Weekly Features/Arts/_bettermee.webp',
    artist: getArtistByFilename('_bettermee'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-10-01',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-10-07',
    createdAt: '2025-10-01',
    updatedAt: '2025-10-07',
  },
];

// Mock memes (main gallery - original content only)
export const mockMemes: Artwork[] = [
  {
    _id: 'meme1',
    title: 'Ahmed\'s Art Wisdom',
    slug: 'ahmeds-art-wisdom',
    description: 'By Ahamedzola',
    imageUrl: '/Artists/Memes/Ahamedzola.webp',
    artist: getArtistByFilename('Ahamedzola.webp'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-28',
    publicationDate: '2025-03-29',
    isFeatured: false,
    createdAt: '2025-03-28',
    updatedAt: '2025-03-29',
  },
  {
    _id: 'meme2',
    title: 'Dio\'s Digital Dilemma',
    slug: 'dios-digital-dilemma',
    description: 'By Diokusumo',
    imageUrl: '/Artists/Memes/Diokusumo.webp',
    artist: getArtistByFilename('Diokusumo.webp'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-27',
    publicationDate: '2025-03-28',
    isFeatured: true,
    createdAt: '2025-03-27',
    updatedAt: '2025-03-28',
  },
  {
    _id: 'meme3',
    title: 'Sai\'s Creative Commentary',
    slug: 'sais-creative-commentary',
    description: 'By Nagasaikurma',
    imageUrl: '/Artists/Memes/Nagasaikurma.webp',
    artist: getArtistByFilename('Nagasaikurma.webp'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-26',
    publicationDate: '2025-03-27',
    isFeatured: false,
    createdAt: '2025-03-26',
    updatedAt: '2025-03-27',
  },
  {
    _id: 'meme4',
    title: 'Fartxe\'s Animated Antics',
    slug: 'fartxes-animated-antics',
    description: 'By Fartxe',
    imageUrl: '/Artists/Memes/Fartxe.gif',
    artist: getArtistByFilename('Fartxe.gif'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-25',
    publicationDate: '2025-03-26',
    isFeatured: false,
    createdAt: '2025-03-25',
    updatedAt: '2025-03-26',
  },
  {
    _id: 'meme5',
    title: 'DT Dude\'s Developer Drama',
    slug: 'dt-dudes-developer-drama',
    description: 'By dt-dude',
    imageUrl: '/Artists/Memes/dt-dude.mp4',
    artist: getArtistByFilename('dt-dude.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-24',
    publicationDate: '2025-03-25',
    isFeatured: false,
    createdAt: '2025-03-24',
    updatedAt: '2025-03-25',
  },
  {
    _id: 'meme6',
    title: 'Kato\'s Creative Comedy',
    slug: 'katos-creative-comedy',
    description: 'By Katohife',
    imageUrl: '/Artists/Memes/Katohife.mp4',
    artist: getArtistByFilename('Katohife.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-23',
    publicationDate: '2025-03-24',
    isFeatured: false,
    createdAt: '2025-03-23',
    updatedAt: '2025-03-24',
  },
  {
    _id: 'meme7',
    title: 'Richard\'s Remarkable Reel',
    slug: 'richards-remarkable-reel',
    description: 'By Richard12',
    imageUrl: '/Artists/Memes/Richard12.mp4',
    artist: getArtistByFilename('Richard12.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-22',
    publicationDate: '2025-03-23',
    isFeatured: false,
    createdAt: '2025-03-22',
    updatedAt: '2025-03-23',
  },
  // Weekly Featured Memes (with flag for preservation when features rotate)
  {
    _id: 'weekly-meme1',
    title: 'Cesar\'s Hilarious Creation',
    slug: 'weekly-hilarious-creation-cesar',
    description: 'By cesar',
    imageUrl: '/Artists/Weekly Features/Memes/cesar.jpg',
    artist: getArtistByFilename('cesar'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme2',
    title: 'Hbhb\'s Meme Magic',
    slug: 'weekly-meme-magic-hbhb',
    description: 'By hbhb',
    imageUrl: '/Artists/Weekly Features/Memes/hbhb.jpg',
    artist: getArtistByFilename('hbhb'),
    medium: mockMediums[1],
    style: mockStyles[2],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme3',
    title: 'Daniviecmi\'s Hilarious Take',
    slug: 'weekly-hilarious-take-daniviecmi',
    description: 'By daniviecmi',
    imageUrl: '/Artists/Weekly Features/Memes/daniviecmi.webp',
    artist: getArtistByFilename('daniviecmi'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme4',
    title: 'Dorock34\'s Video Meme',
    slug: 'weekly-video-meme-dorock34',
    description: 'By dorock34',
    imageUrl: '/Artists/Weekly Features/Memes/dorock34.mp4',
    artist: getArtistByFilename('dorock34'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme5',
    title: 'Hyuga37512\'s Comedy Gold',
    slug: 'weekly-comedy-gold-hyuga37512',
    description: 'By hyuga37512',
    imageUrl: '/Artists/Weekly Features/Memes/hyuga37512.webp',
    artist: getArtistByFilename('hyuga37512'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme6',
    title: 'Karandedhaa\'s Funny Creation',
    slug: 'weekly-funny-creation-karandedhaa',
    description: 'By karandedhaa',
    imageUrl: '/Artists/Weekly Features/Memes/karandedhaa.webp',
    artist: getArtistByFilename('karandedhaa'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[1]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme7',
    title: 'Mofeoluwa2\'s Meme Magic',
    slug: 'weekly-meme-magic-mofeoluwa2',
    description: 'By mofeoluwa2',
    imageUrl: '/Artists/Weekly Features/Memes/mofeoluwa2.webp',
    artist: getArtistByFilename('mofeoluwa2'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[0]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme8',
    title: 'Nafisnin\'s Comedy Creation',
    slug: 'weekly-comedy-creation-nafisnin',
    description: 'By nafisnin',
    imageUrl: '/Artists/Weekly Features/Memes/nafisnin.webp',
    artist: getArtistByFilename('nafisnin'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme9',
    title: 'Travis0n_\'s Hilarious Content',
    slug: 'weekly-hilarious-content-travis0n',
    description: 'By travis0n_',
    imageUrl: '/Artists/Weekly Features/Memes/travis0n_.webp',
    artist: getArtistByFilename('travis0n_'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme-new1',
    title: 'Akashranjan7\'s Fresh Humor',
    slug: 'weekly-fresh-humor-akashranjan7',
    description: 'By akashranjan7',
    imageUrl: '/Artists/Weekly Features/Memes/akashranjan7.mp4',
    artist: getArtistByFilename('akashranjan7'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'weekly-meme-new2',
    title: 'Fudfuudd\'s Comedy Gold',
    slug: 'weekly-comedy-gold-fudfuudd',
    description: 'By fudfuudd',
    imageUrl: '/Artists/Weekly Features/Memes/fudfuudd.mp4',
    artist: getArtistByFilename('fudfuudd'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[1]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'weekly-meme-new3',
    title: 'Gofarhilman\'s Wit',
    slug: 'weekly-wit-gofarhilman',
    description: 'By gofarhilman',
    imageUrl: '/Artists/Weekly Features/Memes/gofarhilman.webp',
    artist: getArtistByFilename('gofarhilman'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'weekly-meme-new4',
    title: 'Kaycee765\'s Humor',
    slug: 'weekly-humor-kaycee765',
    description: 'By kaycee765',
    imageUrl: '/Artists/Weekly Features/Memes/kaycee765.webp',
    artist: getArtistByFilename('kaycee765'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[0]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'weekly-meme-new5',
    title: 'Nanang2712\'s Comedy',
    slug: 'weekly-comedy-nanang2712',
    description: 'By nanang2712',
    imageUrl: '/Artists/Weekly Features/Memes/nanang2712.mp4',
    artist: getArtistByFilename('nanang2712'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'weekly-meme-new6',
    title: 'Trando97\'s Laughs',
    slug: 'weekly-laughs-trando97',
    description: 'By trando97',
    imageUrl: '/Artists/Weekly Features/Memes/trando97.mp4',
    artist: getArtistByFilename('trando97'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'meme-new1',
    title: '0xdivy\'s Meme Art',
    slug: '0xdivy-meme-art',
    description: 'By 0xdivy',
    imageUrl: '/Artists/Memes/0xdivy.webp',
    artist: getArtistByFilename('0xdivy'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[1]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'meme-new2',
    title: '0xdivy\'s Animated Meme',
    slug: '0xdivy-animated-meme',
    description: 'By 0xdivy',
    imageUrl: '/Artists/Memes/0xdivy2.gif',
    artist: getArtistByFilename('0xdivy'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'meme-new3',
    title: 'Akka Pa\'s Video Comedy',
    slug: 'akka-pa-video-comedy',
    description: 'By Akka Pa',
    imageUrl: '/Artists/Memes/Akka Pa.mp4',
    artist: getArtistByFilename('Akka Pa'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'meme-new4',
    title: 'Its_axios\'s Comedy Video',
    slug: 'its-axios-comedy-video',
    description: 'By Its_axios',
    imageUrl: '/Artists/Memes/Its_axios.mp4',
    artist: getArtistByFilename('Its_axios'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[0]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'meme-new5',
    title: 'Siiiuuperman\'s Super Meme',
    slug: 'siiiuuperman-super-meme',
    description: 'By siiiuuperman',
    imageUrl: '/Artists/Memes/siiiuuperman.webp',
    artist: getArtistByFilename('siiiuuperman'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'meme-new6',
    title: 'Srikanth\'s Comedy Creation',
    slug: 'srikanth-comedy-creation',
    description: 'By srikanth',
    imageUrl: '/Artists/Memes/srikanth.mp4',
    artist: getArtistByFilename('srikanth'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[5], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
];

// Mock gifs (main gallery - original content only)
export const mockGifs: Artwork[] = [
  {
    _id: 'gif1',
    title: 'Animated Expression',
    slug: 'animated-expression',
    description: 'By AlexGoldPack',
    imageUrl: '/Artists/Gifs/AlexGoldPack.gif',
    artist: getArtistByFilename('AlexGoldPack.gif'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-20',
    publicationDate: '2025-03-22',
    isFeatured: true,
    createdAt: '2025-03-20',
    updatedAt: '2025-03-22',
  },
  {
    _id: 'gif2',
    title: 'Dynamic Animation',
    slug: 'dynamic-animation',
    description: 'By Bikoy',
    imageUrl: '/Artists/Gifs/Bikoy.mp4',
    artist: getArtistByFilename('Bikoy.mp4'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-19',
    publicationDate: '2025-03-21',
    isFeatured: false,
    createdAt: '2025-03-19',
    updatedAt: '2025-03-21',
  },
  // Weekly Featured Gifs (with flag for preservation when features rotate)
  {
    _id: 'weekly-gif1',
    title: 'Luis\'s Animated Masterpiece',
    slug: 'weekly-animated-masterpiece-luis',
    description: 'By luis',
    imageUrl: '/Artists/Weekly Features/Gifs/luis.gif',
    artist: getArtistByFilename('luis'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-gif1',
    title: 'Feriset\'s Animated Masterpiece',
    slug: 'weekly-animated-masterpiece-feriset',
    description: 'By feriset',
    imageUrl: '/Artists/Weekly Features/Gifs/feriset.gif',
    artist: getArtistByFilename('feriset'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-gif2',
    title: 'Rexleys\'s Dynamic Video',
    slug: 'weekly-dynamic-video-rexleys',
    description: 'By rexleys',
    imageUrl: '/Artists/Weekly Features/Gifs/rexleys.mp4',
    artist: getArtistByFilename('rexleys'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    isWeeklyFeatured: false,
    weeklyFeatureDate: '2025-09-28',
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-gif-new1',
    title: 'Inmemewetrust\'s Video Meme',
    slug: 'weekly-video-meme-inmemewetrust',
    description: 'By inmemewetrust',
    imageUrl: '/Artists/Weekly Features/Gifs/inmemewetrust.mp4',
    artist: getArtistByFilename('inmemewetrust'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'weekly-gif-new2',
    title: 'Peanutskacang\'s Animated Fun',
    slug: 'weekly-animated-fun-peanutskacang',
    description: 'By peanutskacang',
    imageUrl: '/Artists/Weekly Features/Gifs/peanutskacang.gif',
    artist: getArtistByFilename('peanutskacang'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[1]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'weekly-gif-new3',
    title: 'Ped3318\'s GIF Creation',
    slug: 'weekly-gif-creation-ped3318',
    description: 'By ped3318',
    imageUrl: '/Artists/Weekly Features/Gifs/ped3318.gif',
    artist: getArtistByFilename('ped3318'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'weekly-gif-new4',
    title: 'Reff3169\'s Dynamic GIF',
    slug: 'weekly-dynamic-gif-reff3169',
    description: 'By reff3169',
    imageUrl: '/Artists/Weekly Features/Gifs/reff3169.gif',
    artist: getArtistByFilename('reff3169'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[0]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'weekly-gif-new5',
    title: 'Sanjeebdas1979\'s Animation',
    slug: 'weekly-animation-sanjeebdas1979',
    description: 'By sanjeebdas1979',
    imageUrl: '/Artists/Weekly Features/Gifs/sanjeebdas1979.gif',
    artist: getArtistByFilename('sanjeebdas1979'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-29',
    publicationDate: '2025-09-30',
    isFeatured: true,
    isWeeklyFeatured: true,
    weeklyFeatureDate: '2025-09-30',
    createdAt: '2025-09-29',
    updatedAt: '2025-09-30',
  },
  {
    _id: 'gif-new1',
    title: 'Basss_eth\'s Video GIF',
    slug: 'basss-eth-video-gif',
    description: 'By basss_eth',
    imageUrl: '/Artists/Gifs/basss_eth.mp4',
    artist: getArtistByFilename('basss_eth'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[1]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'gif-new2',
    title: 'Grejk\'s Animated Creation',
    slug: 'grejk-animated-creation',
    description: 'By Grejk',
    imageUrl: '/Artists/Gifs/Grejk.gif',
    artist: getArtistByFilename('Grejk'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'gif-new3',
    title: 'Johnathanhnd\'s GIF Art',
    slug: 'johnathanhnd-gif-art',
    description: 'By johnathanhnd',
    imageUrl: '/Artists/Gifs/johnathanhnd.gif',
    artist: getArtistByFilename('johnathanhnd'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[0]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'gif-new4',
    title: 'Kaygon\'s Dynamic GIF',
    slug: 'kaygon-dynamic-gif',
    description: 'By Kaygon',
    imageUrl: '/Artists/Gifs/Kaygon.gif',
    artist: getArtistByFilename('Kaygon'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'gif-new5',
    title: 'Minhhnob\'s Animation',
    slug: 'minhhnob-animation',
    description: 'By minhhnob',
    imageUrl: '/Artists/Gifs/minhhnob.gif',
    artist: getArtistByFilename('minhhnob'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[1]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'gif-new6',
    title: 'Misterche\'s Creative GIF',
    slug: 'misterche-creative-gif',
    description: 'By Misterche',
    imageUrl: '/Artists/Gifs/Misterche.gif',
    artist: getArtistByFilename('Misterche'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'gif-new7',
    title: 'Newera3\'s Next-Gen GIF',
    slug: 'newera3-next-gen-gif',
    description: 'By newera3',
    imageUrl: '/Artists/Gifs/newera3.gif',
    artist: getArtistByFilename('newera3'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'gif-new8',
    title: 'Nook38\'s Animated Art',
    slug: 'nook38-animated-art',
    description: 'By Nook38',
    imageUrl: '/Artists/Gifs/Nook38.gif',
    artist: getArtistByFilename('Nook38'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[0]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
  {
    _id: 'gif-new9',
    title: 'Ricky1414\'s GIF Magic',
    slug: 'ricky1414-gif-magic',
    description: 'By ricky1414',
    imageUrl: '/Artists/Gifs/ricky1414.gif',
    artist: getArtistByFilename('ricky1414'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[1]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-10-05',
    publicationDate: '2025-10-07',
    isFeatured: true,
    isWeeklyFeatured: false,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-07',
  },
];

// WEEKLY FEATURES - SEPARATE ARRAYS (only actual weekly features content)
export const weeklyFeaturedArtworks: Artwork[] = [
  {
    _id: 'weekly-art1',
    title: 'Ceqih\'s Creative Vision',
    slug: 'weekly-creative-vision-ceqih',
    description: 'By ceqih',
    imageUrl: '/Artists/Weekly Features/Arts/ceqih.jpg',
    artist: getArtistByFilename('ceqih'),
    medium: mockMediums[1],
    style: mockStyles[0],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art2',
    title: 'Ciao\'s Digital Masterpiece',
    slug: 'weekly-digital-masterpiece-ciao0910',
    description: 'By ciao0910',
    imageUrl: '/Artists/Weekly Features/Arts/ciao0910.webp',
    artist: getArtistByFilename('ciao0910'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art3',
    title: 'Dark Thinking',
    slug: 'weekly-dark-thinking-darkthgink',
    description: 'By darkthgink',
    imageUrl: '/Artists/Weekly Features/Arts/darkthgink.webp',
    artist: getArtistByFilename('darkthgink'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art4',
    title: 'DLDW Artistic Expression',
    slug: 'weekly-artistic-expression-dldw1314',
    description: 'By dldw1314',
    imageUrl: '/Artists/Weekly Features/Arts/dldw1314.webp',
    artist: getArtistByFilename('dldw1314'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[0], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art5',
    title: 'HRX Vision',
    slug: 'weekly-hrx-vision-hrx0005',
    description: 'By hrx0005',
    imageUrl: '/Artists/Weekly Features/Arts/hrx0005.webp',
    artist: getArtistByFilename('hrx0005'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art6',
    title: 'JDR Creative Design',
    slug: 'weekly-creative-design-jdr525',
    description: 'By jdr525',
    imageUrl: '/Artists/Weekly Features/Arts/jdr525.webp',
    artist: getArtistByFilename('jdr525'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art7',
    title: 'Lueguo Motion Art',
    slug: 'weekly-motion-art-lueguo-video',
    description: 'By lueguo',
    imageUrl: '/Artists/Weekly Features/Arts/lueguo.mp4',
    artist: getArtistByFilename('lueguo'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art8',
    title: 'Lueguo Static Art',
    slug: 'weekly-static-art-lueguo-image',
    description: 'By lueguo',
    imageUrl: '/Artists/Weekly Features/Arts/lueguo.webp',
    artist: getArtistByFilename('lueguo'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art9',
    title: 'May Motion Creation',
    slug: 'weekly-motion-creation-may821',
    description: 'By may821',
    imageUrl: '/Artists/Weekly Features/Arts/may821.mp4',
    artist: getArtistByFilename('may821'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art10',
    title: 'Nova\'s Artistic Vision',
    slug: 'weekly-artistic-vision-novanguyen2802',
    description: 'By novanguyen2802',
    imageUrl: '/Artists/Weekly Features/Arts/novanguyen2802.webp',
    artist: getArtistByFilename('novanguyen2802'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art11',
    title: 'Tinky Viki Creation',
    slug: 'weekly-viki-creation-tinkyviki',
    description: 'By tinkyviki',
    imageUrl: '/Artists/Weekly Features/Arts/tinkyviki.webp',
    artist: getArtistByFilename('tinkyviki'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[1], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
];

export const weeklyFeaturedMemes: Artwork[] = [
  {
    _id: 'weekly-meme1',
    title: 'Dani\'s Humor',
    slug: 'weekly-humor-daniviecmi',
    description: 'By daniviecmi',
    imageUrl: '/Artists/Weekly Features/Memes/daniviecmi.webp',
    artist: getArtistByFilename('daniviecmi'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme2',
    title: 'Dorock\'s Comedy',
    slug: 'weekly-comedy-dorock34',
    description: 'By dorock34',
    imageUrl: '/Artists/Weekly Features/Memes/dorock34.mp4',
    artist: getArtistByFilename('dorock34'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme3',
    title: 'Hyuga\'s Meme Magic',
    slug: 'weekly-meme-magic-hyuga37512',
    description: 'By hyuga37512',
    imageUrl: '/Artists/Weekly Features/Memes/hyuga37512.webp',
    artist: getArtistByFilename('hyuga37512'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme4',
    title: 'Karan\'s Dedhaa',
    slug: 'weekly-dedhaa-karandedhaa',
    description: 'By karandedhaa',
    imageUrl: '/Artists/Weekly Features/Memes/karandedhaa.webp',
    artist: getArtistByFilename('karandedhaa'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[3]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme5',
    title: 'Mofeoluwa\'s Comedy',
    slug: 'weekly-comedy-mofeoluwa2',
    description: 'By mofeoluwa2',
    imageUrl: '/Artists/Weekly Features/Memes/mofeoluwa2.webp',
    artist: getArtistByFilename('mofeoluwa2'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[1], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme6',
    title: 'Nafis\'s Humor',
    slug: 'weekly-humor-nafisnin',
    description: 'By nafisnin',
    imageUrl: '/Artists/Weekly Features/Memes/nafisnin.webp',
    artist: getArtistByFilename('nafisnin'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme7',
    title: 'Travis\'s Meme',
    slug: 'weekly-meme-travis0n',
    description: 'By travis0n_',
    imageUrl: '/Artists/Weekly Features/Memes/travis0n_.webp',
    artist: getArtistByFilename('travis0n_'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
];

export const weeklyFeaturedGifs: Artwork[] = [
  {
    _id: 'weekly-gif1',
    title: 'Feriset\'s Animation',
    slug: 'weekly-animation-feriset',
    description: 'By feriset',
    imageUrl: '/Artists/Weekly Features/Gifs/feriset.gif',
    artist: getArtistByFilename('feriset'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-gif2',
    title: 'Rexley\'s Motion',
    slug: 'weekly-motion-rexleys',
    description: 'By rexleys',
    imageUrl: '/Artists/Weekly Features/Gifs/rexleys.mp4',
    artist: getArtistByFilename('rexleys'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
];

// API Functions for main galleries
export function getMockArtworks(page: number = 1, limit: number = 12) {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedArtworks = mockArtworks.slice(startIndex, endIndex);
  
  return {
    artworks: paginatedArtworks,
    total: mockArtworks.length,
    page,
    limit,
    hasMore: endIndex < mockArtworks.length,
  };
}

export function getMockArtworkBySlug(slug: string): Artwork | null {
  // Search in regular artworks first
  const artwork = mockArtworks.find(artwork => artwork.slug === slug);
  if (artwork) return artwork;
  
  // Search in weekly featured artworks using the filtering approach
  const weeklyArtwork = getMockWeeklyFeaturedArtworks().find(artwork => artwork.slug === slug);
  if (weeklyArtwork) return weeklyArtwork;
  
  // Search in weekly featured memes using the filtering approach
  const weeklyMeme = getMockWeeklyFeaturedMemes().find(artwork => artwork.slug === slug);
  if (weeklyMeme) return weeklyMeme;
  
  // Search in weekly featured gifs using the filtering approach
  const weeklyGif = getMockWeeklyFeaturedGifs().find(artwork => artwork.slug === slug);
  if (weeklyGif) return weeklyGif;
  
  return null;
}

export function getMockMemes(page: number = 1, limit: number = 12) {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedMemes = mockMemes.slice(startIndex, endIndex);
  
  return {
    artworks: paginatedMemes,
    total: mockMemes.length,
    page,
    limit,
    hasMore: endIndex < mockMemes.length,
  };
}

export function getMockMemeBySlug(slug: string): Artwork | null {
  // Search in both regular memes and weekly featured memes
  const allMemes = [...mockMemes, ...weeklyFeaturedMemes];
  return allMemes.find(meme => meme.slug === slug) || null;
}

export function getMockGifs(page: number = 1, limit: number = 12) {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedGifs = mockGifs.slice(startIndex, endIndex);
  
  return {
    artworks: paginatedGifs,
    total: mockGifs.length,
    page,
    limit,
    hasMore: endIndex < mockGifs.length,
  };
}

export function getMockGifBySlug(slug: string): Artwork | null {
  // Search in both regular gifs and weekly featured gifs
  const allGifs = [...mockGifs, ...weeklyFeaturedGifs];
  return allGifs.find(gif => gif.slug === slug) || null;
}

// API Functions for weekly features (separate from main galleries)
export function getMockWeeklyFeaturedArtworks(): Artwork[] {
  return mockArtworks.filter(artwork => artwork.isWeeklyFeatured);
}

export function getMockWeeklyFeaturedMemes(): Artwork[] {
  return mockMemes.filter(meme => meme.isWeeklyFeatured);
}

export function getMockWeeklyFeaturedGifs(): Artwork[] {
  return mockGifs.filter(gif => gif.isWeeklyFeatured);
}

export function getAllWeeklyFeatured(): Artwork[] {
  return [
    ...getMockWeeklyFeaturedArtworks(), 
    ...getMockWeeklyFeaturedMemes(), 
    ...getMockWeeklyFeaturedGifs()
  ];
}

// New functions for cycling system
export function getCurrentWeeklyFeatures(): Artwork[] {
  // Get features from current rotation (2025-10-07 and newer)
  const currentRotationDate = '2025-10-07';
  
  const currentArts = mockArtworks.filter(artwork => 
    artwork.isWeeklyFeatured && 
    artwork.weeklyFeatureDate && 
    artwork.weeklyFeatureDate >= currentRotationDate
  );
  
  const currentMemes = mockMemes.filter(meme => 
    meme.isWeeklyFeatured && 
    meme.weeklyFeatureDate && 
    meme.weeklyFeatureDate >= currentRotationDate
  );
  
  const currentGifs = mockGifs.filter(gif => 
    gif.isWeeklyFeatured && 
    gif.weeklyFeatureDate && 
    gif.weeklyFeatureDate >= currentRotationDate
  );
  
  return [...currentArts, ...currentMemes, ...currentGifs];
}

export function getPreviousWeeklyFeatures(): Artwork[] {
  // Get features from previous rotations (before 2025-10-07)
  const currentRotationDate = '2025-10-07';
  
  const previousArts = mockArtworks.filter(artwork => 
    artwork.isWeeklyFeatured && 
    artwork.weeklyFeatureDate && 
    artwork.weeklyFeatureDate < currentRotationDate
  );
  
  const previousMemes = mockMemes.filter(meme => 
    meme.isWeeklyFeatured && 
    meme.weeklyFeatureDate && 
    meme.weeklyFeatureDate < currentRotationDate
  );
  
  const previousGifs = mockGifs.filter(gif => 
    gif.isWeeklyFeatured && 
    gif.weeklyFeatureDate && 
    gif.weeklyFeatureDate < currentRotationDate
  );
  
  return [...previousArts, ...previousMemes, ...previousGifs];
}

export function getMockRecentArtworks(page: number = 1, limit: number = 12) {
  // Recent artworks now shows previous weekly features + regular artworks
  const previousFeatures = getPreviousWeeklyFeatures();
  const regularArtworks = mockArtworks.filter(artwork => !artwork.isWeeklyFeatured);
  
  // Combine and sort by publication date (newest first)
  const recentContent = [...previousFeatures, ...regularArtworks]
    .sort((a, b) => {
      const dateA = new Date(a.publicationDate || a.createdAt);
      const dateB = new Date(b.publicationDate || b.createdAt);
      return dateB.getTime() - dateA.getTime();
    });
  
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedArtworks = recentContent.slice(startIndex, endIndex);
  
  return {
    artworks: paginatedArtworks,
    total: recentContent.length,
    page,
    limit,
    hasMore: endIndex < recentContent.length,
  };
}

// Mock User for weekly features
const mockCurator: User = {
  _id: 'admin1',
  username: 'curator',
  email: 'curator@riallery.com',
  role: 'curator',
  isActive: true,
  createdAt: '2024-01-01',
  updatedAt: '2024-03-01',
};

// Mock Weekly Features
export const mockWeeklyFeatures: WeeklyFeature[] = [
  {
    _id: '1',
    title: 'Artist Spotlight: Digital Innovators',
    slug: 'digital-innovators-spotlight',
    artist: mockArtists[0], // arishdona
    featuredArtworks: [mockArtworks[0]], // Digital Serenity
    introduction: 'This week, we\'re thrilled to spotlight innovative digital artists from our community. These creators push the boundaries of digital art, blending traditional techniques with cutting-edge technology to create stunning visual experiences.',
    artistNoteQuote: 'Digital art allows us to explore realms that traditional media cannot reach. It\'s about expanding the canvas of human imagination.',
    scheduledDate: '2025-09-28',
    publicationStatus: 'published',
    publishedAt: '2025-09-28',
    createdBy: mockCurator,
    updatedBy: mockCurator,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
];

// API Functions for weekly features
export function getMockCurrentFeature(): WeeklyFeature | null {
  return mockWeeklyFeatures.find(feature => feature.publicationStatus === 'published') || null;
}

export function getMockWeeklyFeatureBySlug(slug: string): WeeklyFeature | null {
  return mockWeeklyFeatures.find(feature => feature.slug === slug) || null;
}

// Navigation function to get previous/next artwork in collection
export function getArtworkNavigation(currentSlug: string, contentType?: string) {
  let collection: Artwork[] = [];
  let baseUrl = '/gallery';
  
  // Determine which collection to use based on content type or by finding the artwork
  if (contentType === 'meme') {
    collection = [...mockMemes, ...weeklyFeaturedMemes];
    baseUrl = '/memes';
  } else if (contentType === 'gif') {
    collection = [...mockGifs, ...weeklyFeaturedGifs];
    baseUrl = '/gifs';
  } else {
    // For artworks, search in all collections to find where the current artwork is
    const artworkInMain = mockArtworks.find(art => art.slug === currentSlug);
    const artworkInWeeklyArt = getMockWeeklyFeaturedArtworks().find(art => art.slug === currentSlug);
    const artworkInWeeklyMemes = getMockWeeklyFeaturedMemes().find(art => art.slug === currentSlug);
    const artworkInWeeklyGifs = getMockWeeklyFeaturedGifs().find(art => art.slug === currentSlug);
    
    if (artworkInMain) {
      collection = mockArtworks;
      baseUrl = '/gallery';
    } else if (artworkInWeeklyArt) {
      collection = getMockWeeklyFeaturedArtworks();
      baseUrl = '/gallery';
    } else if (artworkInWeeklyMemes) {
      collection = getMockWeeklyFeaturedMemes();
      baseUrl = '/memes';
    } else if (artworkInWeeklyGifs) {
      collection = getMockWeeklyFeaturedGifs();
      baseUrl = '/gifs';
    } else {
      // Fallback to main artworks
      collection = mockArtworks;
      baseUrl = '/gallery';
    }
  }
  
  const currentIndex = collection.findIndex(art => art.slug === currentSlug);
  
  if (currentIndex === -1) {
    return { 
      prev: null, 
      next: null, 
      collection: 'unknown', 
      baseUrl,
      currentIndex: 1,
      total: collection.length
    };
  }
  
  const prev = currentIndex > 0 ? collection[currentIndex - 1] : null;
  const next = currentIndex < collection.length - 1 ? collection[currentIndex + 1] : null;
  
  // Determine collection name for display
  let collectionName = 'Gallery';
  if (baseUrl === '/memes') collectionName = 'Memes';
  if (baseUrl === '/gifs') collectionName = 'GIFs';
  
  return {
    prev,
    next,
    collection: collectionName,
    baseUrl,
    currentIndex: currentIndex + 1,
    total: collection.length
  };
}

