import { Artwork, Artist, Medium, Style, Theme, Event, WeeklyFeature, User } from '@/types';

// Mock themes
export const mockThemes: Theme[] = [
  { _id: '1', name: 'Abstract', slug: 'abstract', isSuggested: true },
  { _id: '2', name: 'Portrait', slug: 'portrait', isSuggested: true },
  { _id: '3', name: 'Landscape', slug: 'landscape', isSuggested: true },
  { _id: '4', name: 'Digital', slug: 'digital', isSuggested: true },
  { _id: '5', name: 'Contemporary', slug: 'contemporary', isSuggested: true },
  { _id: '6', name: 'Humor', slug: 'humor', isSuggested: true },
];

// Mock mediums
export const mockMediums: Medium[] = [
  { _id: '1', name: 'Digital Art', slug: 'digital-art' },
  { _id: '2', name: 'Oil Paint', slug: 'oil-paint' },
  { _id: '3', name: 'Acrylic Paint', slug: 'acrylic-paint' },
  { _id: '4', name: 'Watercolor', slug: 'watercolor' },
  { _id: '5', name: 'Mixed Media', slug: 'mixed-media' },
];

// Mock styles
export const mockStyles: Style[] = [
  { _id: '1', name: 'Realistic', slug: 'realistic' },
  { _id: '2', name: 'Impressionist', slug: 'impressionist' },
  { _id: '3', name: 'Surreal', slug: 'surreal' },
  { _id: '4', name: 'Minimalist', slug: 'minimalist' },
  { _id: '5', name: 'Pop Art', slug: 'pop-art' },
  { _id: '6', name: 'Meme', slug: 'meme' },
];

// Mock events
export const mockEvents: Event[] = [
  {
    _id: '1',
    name: 'Spring Art Festival',
    slug: 'spring-art-festival',
    description: 'Annual celebration of emerging artists and their latest works',
    startDate: '2024-03-01',
    endDate: '2024-03-31',
    isActive: true,
  },
  {
    _id: '2',
    name: 'Digital Dreams Challenge',
    slug: 'digital-dreams-challenge',
    description: 'Monthly challenge for digital artists to showcase their creativity',
    startDate: '2024-02-01',
    endDate: '2024-02-29',
    isActive: false,
  },
  {
    _id: '3',
    name: 'Summer Showcase',
    slug: 'summer-showcase',
    description: 'Community showcase featuring the best summer-themed artworks',
    startDate: '2024-06-01',
    endDate: '2024-08-31',
    isActive: true,
  },
];

// Helper function to create artist based on filename
function getArtistByFilename(filename: string): Artist {
  const nameWithoutExt = filename.replace(/\.[^/.]+$/, '');
  const artistName = nameWithoutExt.replace(/[_-]/g, ' ');
  
  return {
    _id: `artist-${nameWithoutExt}`,
    name: artistName,
    slug: nameWithoutExt.toLowerCase(),
    bio: `Creative artist specializing in digital art and visual storytelling.`,
    status: 'active',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  };
}

// Mock artists (main gallery artists)
export const mockArtists: Artist[] = [
  {
    _id: '1',
    name: 'Ahamedzola',
    slug: 'ahamedzola',
    bio: 'Contemporary digital artist known for thought-provoking visual narratives.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '2', 
    name: 'Diokusumo',
    slug: 'diokusumo',
    bio: 'Digital artist creating vibrant and expressive contemporary works.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '3',
    name: 'Nagasaikurma',
    slug: 'nagasaikurma',
    bio: 'Visual storyteller combining traditional themes with modern digital techniques.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '4',
    name: 'Fartxe',
    slug: 'fartxe',
    bio: 'Innovative animator creating engaging visual experiences.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '5',
    name: 'dt-dude',
    slug: 'dt-dude',
    bio: 'Tech-inspired artist creating content that bridges technology and creativity.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '6',
    name: 'Siiiuuper',
    slug: 'siiiuuper',
    bio: 'Dynamic artist known for energetic and vibrant creative expressions.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '7',
    name: 'Sukafunk',
    slug: 'sukafunk',
    bio: 'Multi-media artist exploring the intersection of music and visual art.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '8',
    name: 'NVRL',
    slug: 'nvrl',
    bio: 'Contemporary artist pushing boundaries with innovative digital techniques.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
  {
    _id: '9',
    name: 'Neulpum',
    slug: 'neulpum',
    bio: 'Minimalist artist creating clean and impactful visual compositions.',
    status: 'featured',
    createdAt: '2025-01-20',
    updatedAt: '2025-01-28',
  },
];

// Mock artworks (main gallery - original content only)
export const mockArtworks: Artwork[] = [
  {
    _id: 'art1',
    title: 'Digital Serenity',
    slug: 'digital-serenity',
    description: 'By arishdona',
    imageUrl: '/Artists/Arts/arishdona.webp',
    artist: getArtistByFilename('arishdona.webp'),
    medium: mockMediums[0],
    style: mockStyles[0],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-15',
    publicationDate: '2025-03-18',
    isFeatured: true,
    createdAt: '2025-03-15',
    updatedAt: '2025-03-18',
  },
  {
    _id: 'art2',
    title: 'Contemporary Expression',
    slug: 'contemporary-expression',
    description: 'By itsmeyourvicky',
    imageUrl: '/Artists/Arts/itsmeyourvicky.webp',
    artist: getArtistByFilename('itsmeyourvicky.webp'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-14',
    publicationDate: '2025-03-17',
    isFeatured: false,
    createdAt: '2025-03-14',
    updatedAt: '2025-03-17',
  },
  {
    _id: 'art3',
    title: 'Vadim\'s Vision',
    slug: 'vadims-vision',
    description: 'By vadim064',
    imageUrl: '/Artists/Arts/vadim064.webp',
    artist: getArtistByFilename('vadim064.webp'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[2], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-13',
    publicationDate: '2025-03-16',
    isFeatured: false,
    createdAt: '2025-03-13',
    updatedAt: '2025-03-16',
  },
  {
    _id: 'art4',
    title: 'Animated Artistry',
    slug: 'animated-artistry',
    description: 'By 0xYANDY',
    imageUrl: '/Artists/Arts/0xYANDY.mp4',
    artist: getArtistByFilename('0xYANDY.mp4'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-12',
    publicationDate: '2025-03-15',
    isFeatured: true,
    createdAt: '2025-03-12',
    updatedAt: '2025-03-15',
  },
  {
    _id: 'art5',
    title: 'Dynamic Movement',
    slug: 'dynamic-movement',
    description: 'By Alexeyya',
    imageUrl: '/Artists/Arts/Alexeyya.mp4',
    artist: getArtistByFilename('Alexeyya.mp4'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-11',
    publicationDate: '2025-03-14',
    isFeatured: false,
    createdAt: '2025-03-11',
    updatedAt: '2025-03-14',
  },
  {
    _id: 'art6',
    title: 'Phuong Expression',
    slug: 'phuong-expression',
    description: 'By Phuong',
    imageUrl: '/Artists/Arts/Phuong.webp',
    artist: getArtistByFilename('Phuong.webp'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-10',
    publicationDate: '2025-03-13',
    isFeatured: false,
    createdAt: '2025-03-10',
    updatedAt: '2025-03-13',
  },
  {
    _id: 'art7',
    title: 'Raw Rage',
    slug: 'raw-rage',
    description: 'By rawrage',
    imageUrl: '/Artists/Arts/rawrage.mp4',
    artist: getArtistByFilename('rawrage.mp4'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-09',
    publicationDate: '2025-03-12',
    isFeatured: false,
    createdAt: '2025-03-09',
    updatedAt: '2025-03-12',
  },
  {
    _id: 'art8',
    title: 'Kharather Vision',
    slug: 'kharather-vision',
    description: 'By Kharather',
    imageUrl: '/Artists/Arts/Kharather.mp4',
    artist: getArtistByFilename('Kharather.mp4'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-08',
    publicationDate: '2025-03-11',
    isFeatured: false,
    createdAt: '2025-03-08',
    updatedAt: '2025-03-11',
  },
  {
    _id: 'art9',
    title: 'Phuong\'s Elegance',
    slug: 'phuongs-elegance',
    description: 'By phuong',
    imageUrl: '/Artists/Arts/phuong.mp4',
    artist: getArtistByFilename('phuong.mp4'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-03-07',
    publicationDate: '2025-03-10',
    isFeatured: false,
    createdAt: '2025-03-07',
    updatedAt: '2025-03-10',
  },
];

// Mock memes (main gallery - original content only)
export const mockMemes: Artwork[] = [
  {
    _id: 'meme1',
    title: 'Ahmed\'s Art Wisdom',
    slug: 'ahmeds-art-wisdom',
    description: 'By Ahamedzola',
    imageUrl: '/Artists/Memes/Ahamedzola.webp',
    artist: getArtistByFilename('Ahamedzola.webp'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-28',
    publicationDate: '2025-03-29',
    isFeatured: false,
    createdAt: '2025-03-28',
    updatedAt: '2025-03-29',
  },
  {
    _id: 'meme2',
    title: 'Dio\'s Digital Dilemma',
    slug: 'dios-digital-dilemma',
    description: 'By Diokusumo',
    imageUrl: '/Artists/Memes/Diokusumo.webp',
    artist: getArtistByFilename('Diokusumo.webp'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-27',
    publicationDate: '2025-03-28',
    isFeatured: true,
    createdAt: '2025-03-27',
    updatedAt: '2025-03-28',
  },
  {
    _id: 'meme3',
    title: 'Sai\'s Creative Commentary',
    slug: 'sais-creative-commentary',
    description: 'By Nagasaikurma',
    imageUrl: '/Artists/Memes/Nagasaikurma.webp',
    artist: getArtistByFilename('Nagasaikurma.webp'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-26',
    publicationDate: '2025-03-27',
    isFeatured: false,
    createdAt: '2025-03-26',
    updatedAt: '2025-03-27',
  },
  {
    _id: 'meme4',
    title: 'Fartxe\'s Animated Antics',
    slug: 'fartxes-animated-antics',
    description: 'By Fartxe',
    imageUrl: '/Artists/Memes/Fartxe.gif',
    artist: getArtistByFilename('Fartxe.gif'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-25',
    publicationDate: '2025-03-26',
    isFeatured: false,
    createdAt: '2025-03-25',
    updatedAt: '2025-03-26',
  },
  {
    _id: 'meme5',
    title: 'DT Dude\'s Developer Drama',
    slug: 'dt-dudes-developer-drama',
    description: 'By dt-dude',
    imageUrl: '/Artists/Memes/dt-dude.mp4',
    artist: getArtistByFilename('dt-dude.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-24',
    publicationDate: '2025-03-25',
    isFeatured: false,
    createdAt: '2025-03-24',
    updatedAt: '2025-03-25',
  },
  {
    _id: 'meme6',
    title: 'Kato\'s Creative Comedy',
    slug: 'katos-creative-comedy',
    description: 'By Katohife',
    imageUrl: '/Artists/Memes/Katohife.mp4',
    artist: getArtistByFilename('Katohife.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-23',
    publicationDate: '2025-03-24',
    isFeatured: false,
    createdAt: '2025-03-23',
    updatedAt: '2025-03-24',
  },
  {
    _id: 'meme7',
    title: 'Richard\'s Remarkable Reel',
    slug: 'richards-remarkable-reel',
    description: 'By Richard12',
    imageUrl: '/Artists/Memes/Richard12.mp4',
    artist: getArtistByFilename('Richard12.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-03-22',
    publicationDate: '2025-03-23',
    isFeatured: false,
    createdAt: '2025-03-22',
    updatedAt: '2025-03-23',
  },
];

// Mock gifs (main gallery - original content only)
export const mockGifs: Artwork[] = [
  {
    _id: 'gif1',
    title: 'Animated Expression',
    slug: 'animated-expression',
    description: 'By AlexGoldPack',
    imageUrl: '/Artists/Gifs/AlexGoldPack.gif',
    artist: getArtistByFilename('AlexGoldPack.gif'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-20',
    publicationDate: '2025-03-22',
    isFeatured: true,
    createdAt: '2025-03-20',
    updatedAt: '2025-03-22',
  },
  {
    _id: 'gif2',
    title: 'Dynamic Animation',
    slug: 'dynamic-animation',
    description: 'By Bikoy',
    imageUrl: '/Artists/Gifs/Bikoy.mp4',
    artist: getArtistByFilename('Bikoy.mp4'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-03-19',
    publicationDate: '2025-03-21',
    isFeatured: false,
    createdAt: '2025-03-19',
    updatedAt: '2025-03-21',
  },
];

// WEEKLY FEATURES - SEPARATE ARRAYS (only actual weekly features content)
export const weeklyFeaturedArtworks: Artwork[] = [
  {
    _id: 'weekly-art1',
    title: 'Dynamic Vision',
    slug: 'weekly-dynamic-vision-batuhantkmk',
    description: 'By batuhantkmk',
    imageUrl: '/Artists/Weekly Features/Arts/batuhantkmk.mp4',
    artist: getArtistByFilename('batuhantkmk.mp4'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art2',
    title: 'Digital Harmony',
    slug: 'weekly-digital-harmony-haruvip',
    description: 'By haruvip',
    imageUrl: '/Artists/Weekly Features/Arts/haruvip.webp',
    artist: getArtistByFilename('haruvip.webp'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art3',
    title: 'Immersive Experience',
    slug: 'weekly-immersive-experience-himu-xyz',
    description: 'By himu_xyz',
    imageUrl: '/Artists/Weekly Features/Arts/himu_xyz.mp4',
    artist: getArtistByFilename('himu_xyz.mp4'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art4',
    title: 'Enigmatic Flow',
    slug: 'weekly-enigmatic-flow-lika-enigma',
    description: 'By lika_enigma',
    imageUrl: '/Artists/Weekly Features/Arts/lika_enigma.mp4',
    artist: getArtistByFilename('lika_enigma.mp4'),
    medium: mockMediums[0],
    style: mockStyles[3],
    themes: [mockThemes[1], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art5',
    title: 'Contemporary Vision',
    slug: 'weekly-contemporary-vision-remwasdie',
    description: 'By remwasdie',
    imageUrl: '/Artists/Weekly Features/Arts/remwasdie.webp',
    artist: getArtistByFilename('remwasdie.webp'),
    medium: mockMediums[0],
    style: mockStyles[2],
    themes: [mockThemes[0], mockThemes[2]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art6',
    title: 'Web Innovation',
    slug: 'weekly-web-innovation-web300fa',
    description: 'By web300fa',
    imageUrl: '/Artists/Weekly Features/Arts/web300fa.webp',
    artist: getArtistByFilename('web300fa.webp'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-art7',
    title: 'Digital Expression',
    slug: 'weekly-digital-expression-zll',
    description: 'By zll_1013575110',
    imageUrl: '/Artists/Weekly Features/Arts/zll_1013575110.webp',
    artist: getArtistByFilename('zll_1013575110.webp'),
    medium: mockMediums[0],
    style: mockStyles[1],
    themes: [mockThemes[0], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'artwork',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
];

export const weeklyFeaturedMemes: Artwork[] = [
  {
    _id: 'weekly-meme1',
    title: 'Digital Humor',
    slug: 'weekly-digital-humor-0xdivy',
    description: 'By 0xdivy',
    imageUrl: '/Artists/Weekly Features/Memes/0xdivy.webp',
    artist: getArtistByFilename('0xdivy'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme2',
    title: 'Animated Comedy',
    slug: 'weekly-animated-comedy-0xdivy2',
    description: 'By 0xdivy',
    imageUrl: '/Artists/Weekly Features/Memes/0xdivy2.gif',
    artist: getArtistByFilename('0xdivy'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[3], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme3',
    title: 'Video Meme Magic',
    slug: 'weekly-video-meme-magic-akka-pa',
    description: 'By Akka Pa',
    imageUrl: '/Artists/Weekly Features/Memes/Akka Pa.mp4',
    artist: getArtistByFilename('Akka Pa.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme4',
    title: 'Tech Humor',
    slug: 'weekly-tech-humor-its-axios',
    description: 'By Its_axios',
    imageUrl: '/Artists/Weekly Features/Memes/Its_axios.mp4',
    artist: getArtistByFilename('Its_axios.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme5',
    title: 'Super Meme',
    slug: 'weekly-super-meme-siiiuuperman',
    description: 'By siiiuuperman',
    imageUrl: '/Artists/Weekly Features/Memes/siiiuuperman.webp',
    artist: getArtistByFilename('siiiuuperman.webp'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
  {
    _id: 'weekly-meme6',
    title: 'Srikanth\'s Comedy',
    slug: 'weekly-srikanths-comedy-srikanth',
    description: 'By srikanth',
    imageUrl: '/Artists/Weekly Features/Memes/srikanth.mp4',
    artist: getArtistByFilename('srikanth.mp4'),
    medium: mockMediums[0],
    style: mockStyles[5],
    themes: [mockThemes[2], mockThemes[5]],
    yearCreated: 2025,
    contentType: 'meme',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
];

export const weeklyFeaturedGifs: Artwork[] = [
  {
    _id: 'weekly-gif1',
    title: 'Featured Animation',
    slug: 'weekly-featured-animation-feriset',
    description: 'By feriset',
    imageUrl: '/Artists/Weekly Features/gifs/feriset.gif',
    artist: getArtistByFilename('feriset.gif'),
    medium: mockMediums[0],
    style: mockStyles[4],
    themes: [mockThemes[3], mockThemes[4]],
    yearCreated: 2025,
    contentType: 'gif',
    status: 'approved',
    submissionDate: '2025-09-25',
    publicationDate: '2025-09-28',
    isFeatured: true,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
];

// API Functions for main galleries
export function getMockArtworks(page: number = 1, limit: number = 12) {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedArtworks = mockArtworks.slice(startIndex, endIndex);
  
  return {
    artworks: paginatedArtworks,
    total: mockArtworks.length,
    page,
    limit,
    hasMore: endIndex < mockArtworks.length,
  };
}

export function getMockArtworkBySlug(slug: string): Artwork | null {
  return mockArtworks.find(artwork => artwork.slug === slug) || null;
}

export function getMockMemes(page: number = 1, limit: number = 12) {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedMemes = mockMemes.slice(startIndex, endIndex);
  
  return {
    artworks: paginatedMemes,
    total: mockMemes.length,
    page,
    limit,
    hasMore: endIndex < mockMemes.length,
  };
}

export function getMockMemeBySlug(slug: string): Artwork | null {
  // Search in both regular memes and weekly featured memes
  const allMemes = [...mockMemes, ...weeklyFeaturedMemes];
  return allMemes.find(meme => meme.slug === slug) || null;
}

export function getMockGifs(page: number = 1, limit: number = 12) {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedGifs = mockGifs.slice(startIndex, endIndex);
  
  return {
    artworks: paginatedGifs,
    total: mockGifs.length,
    page,
    limit,
    hasMore: endIndex < mockGifs.length,
  };
}

export function getMockGifBySlug(slug: string): Artwork | null {
  // Search in both regular gifs and weekly featured gifs
  const allGifs = [...mockGifs, ...weeklyFeaturedGifs];
  return allGifs.find(gif => gif.slug === slug) || null;
}

// API Functions for weekly features (separate from main galleries)
export function getMockWeeklyFeaturedArtworks(): Artwork[] {
  return weeklyFeaturedArtworks;
}

export function getMockWeeklyFeaturedMemes(): Artwork[] {
  return weeklyFeaturedMemes;
}

export function getMockWeeklyFeaturedGifs(): Artwork[] {
  return weeklyFeaturedGifs;
}

export function getAllWeeklyFeatured(): Artwork[] {
  return [...weeklyFeaturedArtworks, ...weeklyFeaturedMemes, ...weeklyFeaturedGifs];
}

// Mock User for weekly features
const mockCurator: User = {
  _id: 'admin1',
  username: 'curator',
  email: 'curator@riallery.com',
  role: 'curator',
  isActive: true,
  createdAt: '2024-01-01',
  updatedAt: '2024-03-01',
};

// Mock Weekly Features
export const mockWeeklyFeatures: WeeklyFeature[] = [
  {
    _id: '1',
    title: 'Artist Spotlight: Digital Innovators',
    slug: 'digital-innovators-spotlight',
    artist: mockArtists[0], // arishdona
    featuredArtworks: [mockArtworks[0]], // Digital Serenity
    introduction: 'This week, we\'re thrilled to spotlight innovative digital artists from our community. These creators push the boundaries of digital art, blending traditional techniques with cutting-edge technology to create stunning visual experiences.',
    artistNoteQuote: 'Digital art allows us to explore realms that traditional media cannot reach. It\'s about expanding the canvas of human imagination.',
    scheduledDate: '2025-09-28',
    publicationStatus: 'published',
    publishedAt: '2025-09-28',
    createdBy: mockCurator,
    updatedBy: mockCurator,
    createdAt: '2025-09-25',
    updatedAt: '2025-09-28',
  },
];

// API Functions for weekly features
export function getMockCurrentFeature(): WeeklyFeature | null {
  return mockWeeklyFeatures.find(feature => feature.publicationStatus === 'published') || null;
}

export function getMockWeeklyFeatureBySlug(slug: string): WeeklyFeature | null {
  return mockWeeklyFeatures.find(feature => feature.slug === slug) || null;
}